import test from 'node:test';import assert from 'node:assert/strict';
import worker,{allocationPlan} from '../dist/server/index.js';import {database} from '../scripts/sqlite-adapter.mjs';import {INCLUSION,EXCLUSION,validate,addMonths,addDays,MODULES} from '../src/schema.js';
const DB=database();const origin='https://test.invalid';
async function request(path,method='GET',data,auth=true){const response=await worker.fetch(new Request(origin+'/api/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(auth?{'oai-authenticated-user-id':'test','oai-authenticated-user-email':'test@example.invalid'}:{})},body:data?JSON.stringify(data):undefined}),{DB});return {status:response.status,data:await response.json()}}
const save=(id,module,data,version=0,slot='main')=>request('patients/'+id+'/records','POST',{module,data,version,slot});
function eligible(i){return {screen:{date:'2026-01-01',age:String(40+i%40),sex:i%2?'女':'男',consent:'是',consentDate:'2026-01-01',eligibility:'符合全部纳入标准，且无任何排除标准'},baseline:{tumor:i%2?'胰腺癌':'远端胆管癌',ecog:String(i%3),distance:'3',tbil:String(100+i)},random:{date:'2026-01-03',guidewire:'是',operator:'虚构测试执行人'}}}
test('50 distinct synthetic patients: create, save, randomize once, repeat visits, reload and audit',async()=>{
for(let i=0;i<50;i++){let id='TEST-'+String(i).padStart(4,'0');assert.equal((await request('patients','POST',{id,center:'C0'+(i%6+1)})).status,200);for(const [module,data]of Object.entries(eligible(i)))assert.equal((await save(id,module,data)).status,200);const a=await request('patients/'+id+'/randomize','POST',{});assert.equal(a.status,200);assert.equal(a.data.allocation.randomNo,'R'+String(i+1).padStart(4,'0'));assert.equal((await request('patients/'+id+'/randomize','POST',{})).data.allocation.randomNo,a.data.allocation.randomNo);for(const m of MODULES.filter(m=>!['screen','baseline','random'].includes(m.id))){let data={date:'2026-01-20'};if(m.id==='procedure')data={date:'2026-01-03',diameter:'10',actual:a.data.allocation.arm==='A'?'夹锚定FCSEMS':'UCSEMS'};assert.equal((await save(id,m.id,data,0,m.repeat?'test-1':'main')).status,200);if(m.repeat)assert.equal((await save(id,m.id,{date:'2026-02-01'},0,'test-2')).status,200)}const loaded=(await request('patients/'+id)).data;assert.equal(loaded.patient.id,id);assert.equal(loaded.records.filter(r=>r.module==='ae').length,2);assert.ok((await request('patients/'+id+'/audit')).data.length>10)}assert.equal((await request('patients')).data.patients.length,50)});
test('negative cases: missing auth, duplicate patient, ineligible, invalid option, stale write, immutable allocation',async()=>{
assert.equal((await request('patients','GET',null,false)).status,401);assert.equal((await request('patients','POST',{id:'TEST-0000',center:'C02'})).status,409);assert.equal((await request('patients','POST',{id:'NEGATIVE',center:'C01'})).status,200);assert.equal((await request('patients/NEGATIVE/randomize','POST',{})).status,400);assert.equal((await save('NEGATIVE','baseline',{ecog:'9'})).status,400);assert.equal((await save('NEGATIVE','screen',{date:'2026-02-30'})).status,400);assert.equal((await save('NEGATIVE','baseline',{ecog:'1'})).status,200);assert.equal((await save('NEGATIVE','baseline',{ecog:'2'})).status,409);assert.equal((await save('TEST-0000','baseline',{ecog:'2'},1)).status,409);assert.throws(()=>DB.sqlite.exec("DELETE FROM allocations WHERE patient='TEST-0000'"));assert.throws(()=>DB.sqlite.exec("UPDATE allocations SET arm='B' WHERE patient='TEST-0000'"));assert.throws(()=>DB.sqlite.exec('DELETE FROM audit'));});
test('concurrent calls allocate once and do not duplicate random numbers',async()=>{for(let i=0;i<3;i++){let id='CONCURRENT-'+i;await request('patients','POST',{id,center:'C01'});for(const [module,data]of Object.entries(eligible(i)))await save(id,module,data)}const results=await Promise.all(Array.from({length:12},(_,i)=>request('patients/CONCURRENT-'+i%3+'/randomize','POST',{})));results.forEach(r=>assert.equal(r.status,200));const rows=DB.sqlite.prepare("SELECT * FROM allocations WHERE patient LIKE 'CONCURRENT-%'").all();assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>r.seq)).size,3)});
test('algorithm ratios, tie, limits, calendars and defined option validation',()=>{assert.equal(allocationPlan([],'C01','P',.49).arm,'A');assert.equal(allocationPlan([],'C01','P',.5).arm,'B');assert.equal(allocationPlan([{arm:'A',center:'C01',stratum:'P'}],'C01','P',.21).arm,'B');let rows=[];for(let i=0;i<272;i++){const center='C0'+(i%6+1),stratum=i%2?'P':'NP';const plan=allocationPlan(rows,center,stratum,(i*37%100)/100);rows.push({arm:plan.arm,center,stratum})}assert.equal(rows.filter(r=>r.arm==='A').length,136);assert.equal(rows.filter(r=>r.arm==='B').length,136);assert.throws(()=>allocationPlan(rows,'C01','P',.5));assert.equal(addMonths('2026-01-31',1),'2026-02-28');assert.equal(addDays('2026-01-01',180),'2026-06-30');assert.ok(validate('ae',{severity:'无'}).length);assert.ok(validate('baseline',{tbil:'-1'}).length)});
