const { chromium }=require('C:/Users/16546/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Users/16546/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe'});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.getByText('服务器连接成功。请选择患者或建立新档案。',{exact:true}).waitFor();let id='UI-TEST-'+Date.now();await page.getByLabel('新患者住院号').fill(id);await page.getByRole('button',{name:'建立患者档案',exact:true}).click();await page.getByText('患者档案已建立。请填写筛选与知情同意。',{exact:true}).waitFor();await page.getByLabel('年龄（岁）',{exact:true}).fill('55');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：入院/).waitFor();await page.reload();await page.getByLabel('已保存患者（服务器）').selectOption(id);await page.getByText('已读取服务器记录',{exact:true}).waitFor();if(await page.getByLabel('年龄（岁）',{exact:true}).inputValue()!=='55')throw Error('Reload lost saved age');await page.getByLabel('已签署知情同意',{exact:true}).selectOption('是');await page.getByLabel('知情同意日期',{exact:true}).fill('2026-01-01');await page.getByLabel('纳入 / 排除标准核对',{exact:true}).selectOption('符合全部纳入标准，且无任何排除标准');if(await page.locator('[name^="in"],[name^="ex"]').count()>1)throw Error('Unexpected legacy eligibility controls');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：入院/).waitFor();await page.locator('[data-view="baseline"]').click();await page.getByLabel('ECOG评分',{exact:true}).selectOption('1');await page.getByLabel('原发肿瘤类型',{exact:true}).selectOption('胰腺癌');await page.getByLabel('梗阻距肝门汇合处（cm）',{exact:true}).fill('3');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：术前/).waitFor();await page.locator('[data-view="surgery"]').click();await page.getByLabel('ERCP日期',{exact:true}).fill('2026-01-03');await page.getByLabel('导丝已成功跨越狭窄',{exact:true}).selectOption('是');await page.getByLabel('随机执行人姓名',{exact:true}).fill('虚构测试执行人');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'保存并执行随机化',exact:true}).click();await page.getByText(/随机化成功：R/).waitFor();const allocated=await page.locator('#allocationBanner').innerText();if(!/已随机化：.*(试验组|对照组)/.test(allocated))throw Error('Missing treatment group');await page.locator('[data-module="procedure"]').click();await page.getByLabel('是否按随机组方案完成',{exact:true}).selectOption('是');if(!await page.getByLabel('实际支架直径（mm）',{exact:true}).isDisabled())throw Error('Fixed diameter editable');if(await page.getByLabel('实际支架直径（mm）',{exact:true}).inputValue()!=='10')throw Error('Wrong fixed diameter');await page.getByLabel('支架置入日期',{exact:true}).fill('2026-01-03');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：手术/).waitFor();await page.reload();await page.getByLabel('已保存患者（服务器）').selectOption(id);await page.getByText('已读取服务器记录',{exact:true}).waitFor();if(await page.locator('#allocationBanner').innerText()!==allocated)throw Error('Allocation changed on reload');await page.locator('[data-view="early"]').click();await page.locator('[data-module="week2"]').click();await page.getByLabel('实际随访日期',{exact:true}).fill('2026-01-17');await page.getByLabel('第14天TBIL（μmol/L）',{exact:true}).fill('40');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：术后2周/).waitFor();const dp=page.waitForEvent('download');await page.getByRole('button',{name:'下载患者全部记录 CSV',exact:true}).click();const download=await dp;const path=await download.path(),csv=fs.readFileSync(path,'utf8');if(!csv.includes('55')||!csv.includes('2026-01-17')||!csv.includes(id))throw Error('CSV missing saved content');const moduleDownload=page.waitForEvent('download');await page.getByRole('button',{name:'下载本模块 CSV',exact:true}).click();await moduleDownload;await page.locator('[data-view="baseline"]').click();
await page.getByText('评分备注：展开查看 ECOG 0–5分',{exact:true}).click();
if(!await page.getByText(/清醒时间超过一半在床上或椅上/).isVisible())throw Error('ECOG help missing');
await page.getByText('分期备注：展开查看 TNM 填写方法与癌种差异',{exact:true}).click();
if(!await page.locator('summary').filter({hasText:/^远端胆管癌$/}).isVisible())throw Error('TNM cancer-specific help missing');
await page.locator('[data-module="qol"]').click();
if(await page.getByLabel('评估时间点',{exact:true}).inputValue()!=='基线'||!await page.getByLabel('评估时间点',{exact:true}).isDisabled())throw Error('Baseline QoL context missing');
await page.getByLabel('实际评估日期',{exact:true}).fill('2026-01-02');
await page.getByLabel('量表类型',{exact:true}).selectOption('两者');
await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();
await page.getByText(/保存成功：生活质量/).waitFor();
await page.locator('[data-view="month3"]').click();await page.locator('[data-module="qol"]').click();
if(await page.getByLabel('评估时间点',{exact:true}).inputValue()!=='3月'||await page.getByLabel('实际评估日期',{exact:true}).inputValue())throw Error('QoL visits mixed');
await page.getByLabel('实际评估日期',{exact:true}).fill('2026-04-03');
await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：生活质量/).waitFor();
await page.locator('[data-module="therapy"]').click();
if(await page.getByLabel('所属访视',{exact:true}).inputValue()!=='术后3个月')throw Error('Medication context missing');
await page.getByLabel('记录日期',{exact:true}).fill('2026-04-03');await page.getByLabel('化疗方案',{exact:true}).fill('仅用于软件测试的虚构方案');
await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：用药/).waitFor();
await page.locator('[data-view="month6"]').click();await page.locator('[data-module="therapy"]').click();
if(await page.getByLabel('化疗方案',{exact:true}).inputValue())throw Error('Medication leaked into another visit');
await page.locator('[data-view="early"]').click();
if(await page.getByLabel('评价时点',{exact:true}).inputValue()!=='7天')throw Error('7day context missing');
await page.getByLabel('采血 / 评价日期',{exact:true}).fill('2026-01-10');
await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：术后早期/).waitFor();
await page.locator('[data-pane="2"]').click();
if(await page.getByLabel('评价时点',{exact:true}).inputValue()!=='21天'||await page.getByLabel('采血 / 评价日期',{exact:true}).inputValue())throw Error('Early dates mixed');
await page.locator('[data-view="surgery"]').click();
if(!await page.getByRole('button',{name:'中央随机分组 · 已分组',exact:true}).isVisible())throw Error('Allocation tab not explicit');
await page.getByText('随机化怎么做？竞争入组与区组有什么区别？',{exact:true}).click();
if(!await page.getByText(/不采用固定区组随机/).isVisible())throw Error('Method explanation missing');
const pendingId='UI-PENDING-'+Date.now();await page.getByLabel('新患者住院号').fill(pendingId);await page.getByRole('button',{name:'建立患者档案',exact:true}).click();await page.getByText('患者档案已建立。请填写筛选与知情同意。',{exact:true}).waitFor();
await page.locator('[data-view="surgery"]').click();
await page.getByLabel('ERCP日期',{exact:true}).fill('2026-01-03');
await page.getByLabel('导丝已成功跨越狭窄',{exact:true}).selectOption('是');
await page.getByLabel('随机执行人姓名',{exact:true}).fill('虚构执行人');
await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();
await page.getByText('随机化资料已保存，但尚未分组。请点击“保存并执行随机化”。',{exact:true}).waitFor();
if(!await page.getByRole('button',{name:'中央随机分组 · 未分组',exact:true}).isVisible())throw Error('Saved random form falsely implies allocation');
await page.getByRole('button',{name:'保存并执行随机化',exact:true}).click();
if(!await page.locator('#status').innerText().then(t=>t.includes('基线')))throw Error('Missing readiness feedback');
await page.getByRole('button',{name:'去入院筛选',exact:true}).click();
if(!await page.getByLabel('年龄（岁）',{exact:true}).isVisible())throw Error('Readiness jump broken');
if(await page.locator('#moduleForm .fields > [data-field]').count()!==await page.locator('#moduleForm .field-guide').count())throw Error('A field lacks guidance');
await page.getByLabel('年龄（岁）',{exact:true}).fill('54');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：入院/).waitFor();
await page.getByLabel('年龄（岁）',{exact:true}).fill('55');await page.getByRole('button',{name:'保存本模块到服务器',exact:true}).click();await page.getByText(/保存成功：入院/).waitFor();
await page.locator('[data-history="age"] summary').click();await page.locator('[data-history="age"] .history-content').getByText(/54 → 55/).waitFor();
if(!await page.locator('[data-history="age"]').innerText().then(t=>t.includes('test@example.invalid')))throw Error('Field history missing actor');
await page.locator('[data-history="sex"] summary').click();await page.locator('[data-history="sex"] .history-content').getByText(/尚无已保存的值变更记录/).waitFor();
await page.locator('[data-view="surgery"]').click();
fs.mkdirSync('test-output',{recursive:true});await page.screenshot({path:'test-output/desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-output/mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');if(errors.length)throw Error(errors.join(';'));console.log(JSON.stringify({passed:true,reload:true,downloads:2,mobileOverflow:false,consoleErrors:errors,syntheticPatient:id}));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
