const $=id=>document.getElementById(id),escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=null,moduleId='screen',slot='main',dirty=false;
function status(text,error=false){$('status').textContent=text;$('status').className='status'+(error?' error':'')}
async function api(path,method='GET',data){const response=await fetch('/api/'+path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});let r;try{r=await response.json()}catch{throw Error('服务器没有返回数据；请保留输入后重试')}if(!response.ok)throw Error(r.error||'操作失败');return r}
const m=()=>MODULES.find(x=>x.id===moduleId),rec=()=>current?.records.find(x=>x.module===moduleId&&x.slot===slot),draftKey=()=>`mdbo-draft-v2:${current?.patient.id}:${moduleId}:${slot}`;
const fmt=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false}):'未保存';
function collect(){const form=$('moduleForm');return Object.fromEntries(m().fields.map(f=>[f.id,form?.elements.namedItem(f.id)?.value??'']))}
function safeLeave(){return !dirty||confirm('当前模块有未保存内容。离开前可先点击“保存本模块”。仍要切换吗？（恢复草稿会保留）')}
function nav(){ $('nav').innerHTML=MODULES.map(x=>`<button data-module="${x.id}" class="${x.id===moduleId?'active':''}">${escapeHtml(x.title)} ${current?.records.some(r=>r.module===x.id)?'<span class="saved">✓</span>':''}</button>`).join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!safeLeave())return;moduleId=b.dataset.module;slot=m().repeat?current?.records.find(r=>r.module===moduleId)?.slot||crypto.randomUUID():'main';dirty=false;render()})}
function info(){if(!current)return;$('identity').textContent=`住院号 ${current.patient.id} ｜ ${CENTERS[current.patient.center]} ｜ ${current.allocation?.randomNo||'尚未随机化'}`}
function input(f,data,locked){const id='field-'+f.id,val=data[f.id]??'',base=`id="${id}" name="${f.id}" ${locked?'disabled':''}`;let control=f.type==='select'?`<select ${base}><option value="">请选择 / 尚未采集</option>${f.options.map(x=>`<option value="${escapeHtml(x)}" ${val===x?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea ${base}>${escapeHtml(val)}</textarea>`:`<input ${base} type="${f.type}" value="${escapeHtml(val)}" ${f.type==='number'?`step="${f.integer?'1':'any'}" min="${f.min??0}" ${f.max!=null?'max="'+f.max+'"':''}`:''}>`;return `<div ${f.type==='textarea'?'class="full"':''} data-field="${f.id}"><label for="${id}">${escapeHtml(f.label)}</label>${control}${f.hint?`<small>${escapeHtml(f.hint)}</small>`:''}</div>`}
function schedule(){const date=current?.records.find(r=>r.module==='procedure')?.data.date;if(!m().day&&!m().month)return '';if(!date)return '<div class="datebox">保存支架置入日期后，自动显示计划随访日和窗口。</div>';const target=m().day?addDays(date,m().day):addMonths(date,m().month),window=m().window;return `<div class="datebox">计划日期：<strong>${target}</strong>${window?` ｜ 允许窗口 ${addDays(target,-window)} 至 ${addDays(target,window)}`:'（置入后第180天）'}${moduleId==='month6'?`<br>主要终点第180天：${addDays(date,180)}，与6个日历月分别记录。`:''}<div id="windowCheck" class="hint"></div></div>`}
function randomInfo(){const a=current.allocation;if(a)return `<div class="result"><strong>${escapeHtml(a.treatment)}</strong>随机号：${a.randomNo} ｜ 受试者编号：${a.subjectNo}<br>锁定时间：${fmt(a.at)} ｜ 执行人：${escapeHtml(a.operator)}<br>分层：${a.center} / ${a.stratum==='P'?'胰腺癌':'非胰腺癌'}<p>该分配已固定，不会因刷新或再次点击而改变。</p></div>`;const errors=eligibility(current.records);return `<div class="notice"><strong>尚未随机化</strong><p>1. 保存筛选和基线 → 2. 确认导丝已跨越狭窄并保存本模块 → 3. 点击下方正式随机化。</p><p>${errors.length?'待完成：'+escapeHtml(errors.join('；')):'资格核对通过，可以申请正式随机化。'}</p></div><button type="button" class="primary" id="randomize" ${errors.length?'disabled':''}>执行正式随机化并锁定</button><p class="hint">采用你确认获批的Excel动态随机法：总体 / 中心 / 肿瘤层平衡，80%偏向平衡组；平分时50% / 50%。每组136例，总计272例。分组由服务器生成。</p>`}
function render(){nav();info();if(!current){$('module').innerHTML='<h2>先打开一位患者</h2><p class="empty">顶部建立患者档案后，从左侧按时间顺序填写。保存位置、随机结果和下载入口会一直清楚显示。</p>';return}const existing=rec(),locked=Boolean(current.allocation&&['screen','baseline','random'].includes(moduleId));let data=existing?.data||{},draft=null;try{draft=JSON.parse(localStorage.getItem(draftKey())||'null')}catch{}let restore=draft&&!locked&&JSON.stringify(draft.data)!==JSON.stringify(data);if(restore){data=draft.data;dirty=true}
$('module').innerHTML=`<div class="module-head"><h2>${escapeHtml(m().title)}</h2><small>${escapeHtml(m().source)} ｜ 保存位置：服务器数据库</small><p class="hint" id="saveInfo">${existing?'上次保存：'+fmt(existing.updated)+' · 第'+existing.version+'版':'尚未保存本记录'}</p></div>${restore?'<div class="notice">已恢复本浏览器未保存输入，请核对后保存到服务器。</div>':''}${m().repeat?`<div class="recordbar"><select aria-label="此模块不同日期的记录" id="recordSelect"><option value="${slot}">${existing?'当前：'+(existing.data.date||'未填日期'):'新记录（未保存）'}</option>${current.records.filter(x=>x.module===moduleId&&x.slot!==slot).map(x=>`<option value="${x.slot}">${escapeHtml(x.data.date||'未填日期')} ${escapeHtml(x.data.time||x.data.event||'')}</option>`).join('')}</select><button id="newRecord">＋ 新增一条记录</button></div>`:''}${schedule()}${moduleId==='random'?randomInfo():''}${moduleId==='procedure'?`<div class="result">随机分配：${escapeHtml(current.allocation?.treatment||'尚未随机化，请先完成中央随机化模块')}<p class="hint">实际操作请如实记录；随机组别与实际治疗分别保存。</p></div>`:''}${moduleId==='month1'?'<p class="notice">30天并发症独立核对；若本次随访早于第30天，请在观察期结束后补全，勿提前填“无”。</p>':''}${locked?'<p class="notice">随机化依据已锁定，只读显示。</p>':''}<form id="moduleForm" novalidate><div class="fields">${m().fields.map(f=>input(f,data,locked)).join('')}</div></form><p class="result" id="derived" ${['week2','clinical'].includes(moduleId)?'':'hidden'}></p><div id="checks" class="hint"></div><div class="module-actions"><button id="saveModule" class="primary" ${locked?'disabled':''}>保存本模块到服务器</button><button id="exportModule">下载本模块 CSV</button><span id="dirty" class="${dirty?'dirty':'saved'}">${dirty?'有未保存内容':existing?'已保存':'待填写'}</span></div>`;
$('moduleForm').onsubmit=e=>e.preventDefault();$('moduleForm').addEventListener('input',()=>{dirty=true;$('dirty').textContent='有未保存内容';$('dirty').className='dirty';try{localStorage.setItem(draftKey(),JSON.stringify({data:collect(),at:new Date().toISOString()}))}catch{status('浏览器草稿空间不足，请及时保存到服务器',true)}computed()});$('saveModule').onclick=saveModule;$('exportModule').onclick=()=>downloadCsv([rowRecord(collect(),m(),slot,dirty?'未保存草稿':'已保存')],m().id);if($('randomize'))$('randomize').onclick=randomize;if($('newRecord'))$('newRecord').onclick=()=>{if(!safeLeave())return;slot=crypto.randomUUID();dirty=false;render()};if($('recordSelect'))$('recordSelect').onchange=e=>{if(!safeLeave()){e.target.value=slot;return}slot=e.target.value;dirty=false;render()};computed()}
function computed(){const data=collect();$('derived').textContent=derived(moduleId,data,current.records);const procedure=current.records.find(r=>r.module==='procedure')?.data||{};let warnings=[];if($('windowCheck')&&data.date&&procedure.date){const target=m().day?addDays(procedure.date,m().day):addMonths(procedure.date,m().month);$('windowCheck').textContent=m().window&&(data.date<addDays(target,-m().window)||data.date>addDays(target,m().window))?'实际日期在窗口外：可如实记录，请补充原因。':'实际日期已填写。'}if(moduleId==='procedure'){if(data.diameter&&+data.diameter!==10)warnings.push('直径与方案10mm不一致');if(current.allocation?.arm==='A'&&(data.clip!=='是'||(data.clipCount&&+data.clipCount!==2)))warnings.push('试验组方案为2枚夹锚定');if(current.allocation?.arm==='B'&&data.clip==='是')warnings.push('对照组不实施夹锚定');if(data.exposure&&(+data.exposure<5||+data.exposure>10))warnings.push('外露长度超出方案约5–10mm');}if(moduleId==='baseline'&&data.date&&procedure.date&&(data.date<addDays(procedure.date,-7)||data.date>procedure.date))warnings.push('术前检验日期不在术前7天内');if(moduleId==='ae'&&data.sae&&data.sae!=='否'&&(!data.reported||data.reported==='不适用'||!data.reportedAt))warnings.push('SAE需填写上报情况和时间；方案要求获知后24小时内上报');if(moduleId==='ae'&&data.severity==='致死'&&data.sae==='否')warnings.push('致死事件与“非SAE”冲突，请核对');if(moduleId==='month1'&&data.reviewDate&&procedure.date&&data.reviewDate<addDays(procedure.date,30))warnings.push('尚未完成完整30天观察');if(data.suspectedRbo==='是')warnings.push('请增加RBO事件记录');if(data.ae==='有')warnings.push('请增加AE/SAE记录');$('checks').textContent=warnings.length?'核对提示：'+warnings.join('；'):''}
async function saveModule(){const data=collect(),errors=validate(moduleId,data);if(errors.length)return status(errors.join('；'),true);const btn=$('saveModule');btn.disabled=true;try{current=await api('patients/'+encodeURIComponent(current.patient.id)+'/records','POST',{module:moduleId,slot,data,version:rec()?.version||0});localStorage.removeItem(draftKey());dirty=false;render();status('保存成功：'+m().title+'。已写入服务器，重新打开可继续填写。')}catch(e){status(e.message,true);btn.disabled=false}}
async function randomize(){if(dirty)return status('请先保存本模块，再进行随机化',true);if(!confirm('确认此患者知情同意、入排标准及导丝跨越狭窄均已核实？正式随机化一经成功，随机号和分组不可重抽或回收。'))return;const b=$('randomize');b.disabled=true;try{current=await api('patients/'+encodeURIComponent(current.patient.id)+'/randomize','POST',{});dirty=false;render();status('随机化成功：'+current.allocation.randomNo+'，'+current.allocation.treatment)}catch(e){status(e.message,true);b.disabled=false}}
function rowRecord(data,module,slot,state){return {module,slot,data,state}}
function download(content,type,name){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);status('已发起下载：'+name+'。请查看浏览器下载记录；若选择保存位置，以你选择的目录为准。')}
function csvSafe(v){let s=String(v??'');if(/^[=+\-@\t\r\n]/.test(s)||/^0\d+$/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function downloadCsv(records,suffix){const p=current.patient,a=current.allocation;const rows=[['住院号','中心代码','中心名称','随机号','随机组别','受试者编号','随机锁定时间','随机执行人','模块','记录ID','实际日期','字段代码','字段名称','值','保存状态']];for(const r of records)for(const f of r.module.fields)rows.push([p.id,p.center,CENTERS[p.center],a?.randomNo||'',a?.treatment||'',a?.subjectNo||'',a?.at||'',a?.operator||'',r.module.title,r.slot,r.data.date||'',f.id,f.label,r.data[f.id]??'',r.state]);download('\ufeff'+rows.map(r=>r.map(csvSafe).join(',')).join('\r\n'),'text/csv;charset=utf-8',`MDBO_${p.id}_${suffix}_${new Date().toISOString().slice(0,10)}.csv`)}
async function fresh(){if(!current)throw Error('请先选择患者');return api('patients/'+encodeURIComponent(current.patient.id))}
$('downloadAll').onclick=async()=>{try{const p=await fresh();downloadCsv(p.records.map(r=>rowRecord(r.data,MODULES.find(m=>m.id===r.module),r.slot,'已保存 v'+r.version)),'全部记录');if(dirty)status('已下载服务器保存版本；当前模块仍有未保存内容，请先保存后再下载全部记录。')}catch(e){status(e.message,true)}};
$('backup').onclick=async()=>{try{const p=await fresh();download(JSON.stringify({format:'MDBO-CRF',version:2,exportedAt:new Date().toISOString(),...p},null,2),'application/json',`MDBO_${p.patient.id}_完整备份.json`)}catch(e){status(e.message,true)}};
$('audit').onclick=async()=>{try{if(!current)throw Error('请先选择患者');const r=await api('patients/'+encodeURIComponent(current.patient.id)+'/audit');download(JSON.stringify(r,null,2),'application/json',`MDBO_${current.patient.id}_操作日志.json`)}catch(e){status(e.message,true)}};
async function list(){const r=await api('patients');$('patientSelect').innerHTML='<option value="">选择已保存患者</option>'+r.patients.map(x=>`<option value="${escapeHtml(x.id)}">${escapeHtml(x.id)} · ${escapeHtml(x.center)}</option>`).join('');$('storage').textContent='已连接 · 服务器保存';return r}
$('patientSelect').onchange=async e=>{if(!safeLeave()){e.target.value=current?.patient.id||'';return}if(!e.target.value)return;try{current=await api('patients/'+encodeURIComponent(e.target.value));moduleId='screen';slot='main';dirty=false;render();status('已读取服务器记录')}catch(e){status(e.message,true)}};
$('create').onclick=async()=>{if(!safeLeave())return;const id=$('hospital').value.trim(),center=$('center').value;if(!id)return status('请填写住院号',true);try{current=await api('patients','POST',{id,center});await list();$('patientSelect').value=id;moduleId='screen';slot='main';dirty=false;render();status('患者档案已建立。请填写筛选与知情同意。')}catch(e){status(e.message,true)}};
$('center').innerHTML=Object.entries(CENTERS).map(([k,v])=>`<option value="${k}">${k} · ${v}</option>`).join('');window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});render();list().then(()=>status('服务器连接成功。请选择患者或建立新档案。')).catch(e=>{status(e.message,true);$('storage').textContent='未连接 · 尚未保存';$('patientSelect').innerHTML='<option value="">连接失败，请刷新重试</option>'});
