const $=id=>document.getElementById(id),escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=null,moduleId='screen',viewId='screen',paneIndex=0,slot='main',dirty=false,busy=false;
const view=()=>WORKFLOW.find(x=>x.id===viewId),activePane=()=>view().panes[paneIndex];
function matchingRecords(){return recordsForPane(current?.records||[],activePane())}
function switchPane(nextView,index=0){if(!safeLeave())return;viewId=nextView;paneIndex=index;moduleId=activePane().module;slot=m().repeat?matchingRecords()[0]?.slot||crypto.randomUUID():'main';dirty=false;render()}
function paneTitle(){return view().title+' · '+activePane().label}
function tabs(){const button=(p,i)=>'<button type="button" data-pane="'+i+'" data-module="'+p.module+'" class="'+(i===paneIndex?'active':'')+'">'+escapeHtml(p.label)+(p.module==='random'?' · '+allocationLabel(current.allocation):'')+'</button>';return '<div class="visit-tabs" aria-label="本次访视内容">'+view().panes.map((p,i)=>p.optional?'<details class="optional-tests" '+(i===paneIndex?'open':'')+'><summary>其他已有检验（可选）</summary><p class="hint">不是新增访视，不要求额外抽血。有现成检验资料时再记录。</p>'+button(p,i)+'</details>':button(p,i)).join('')+'</div>'}
function legacyTherapy(){const key=moduleId==='therapy'?'visit':'time',history=current.records.filter(r=>r.module===moduleId&&(!r.data[key]||moduleId==='therapy'&&activePane().context==='围术期'&&r.data.visit!=='围术期'&&PERIOP_FIELDS.some(k=>r.data[k])));return history.length?'<div class="notice"><label for="legacyTherapy">未归属时间点的历史记录（不会自动改写）</label><select id="legacyTherapy"><option value="">选择旧记录查看或手动归类</option>'+history.map(r=>'<option value="'+r.slot+'">'+escapeHtml(r.data.date||'未填日期')+' · 历史记录</option>').join('')+'</select><small>核对后选择所属访视/时间点再保存；不归类也会保留并导出。</small></div>':''}
function status(text,error=false){$('status').textContent=text;$('status').className='status'+(error?' error':'')}
async function api(path,method='GET',data){const response=await fetch('/api/'+path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});let r;try{r=await response.json()}catch{throw Error('服务器没有返回数据；请保留输入后重试')}if(!response.ok)throw Error(r.error||'操作失败');return r}
const m=()=>MODULES.find(x=>x.id===moduleId),rec=()=>current?.records.find(x=>x.module===moduleId&&x.slot===slot),draftKey=()=>`mdbo-draft-v2:${current?.patient.id}:${moduleId}:${slot}`;
const fmt=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false}):'未保存';
function setBusy(value){busy=value;for(const e of document.querySelectorAll('button,select,input,textarea')){if(value){e.dataset.wasDisabled=String(e.disabled);e.disabled=true}else if(e.dataset.wasDisabled!==undefined){e.disabled=e.dataset.wasDisabled==='true';delete e.dataset.wasDisabled}}if(!value&&current&&$('moduleForm'))computed()}
function criteriaHelp(){return '<details><summary>查看纳入 / 排除标准（仅供核对，无需逐条填写）</summary><h3>纳入：须全部满足</h3><ol>'+INCLUSION.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ol><h3>排除：不得存在任一项</h3><ol>'+EXCLUSION.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ol></details>'}
function liveEligibility(){return current.records.filter(x=>x.module!==moduleId).concat({module:moduleId,data:collect()})}
function procedureRequirements(){const p=procedurePlan(current.allocation?.arm);if(!p)return '<p class="notice">尚未分组。随机化完成后，两组对应的方案要求会自动固定。</p>';return '<div class="result"><strong>本组固定方案要求（只读）</strong><div>支架：'+escapeHtml(p.actual)+'；直径10mm；跨乳头放置。</div><div>'+(current.allocation.arm==='A'?'夹锚定：十二指肠侧，2枚可重复开闭软组织夹；远端外露约5–10mm。':'不实施夹锚定；支架长度选择及释放方式与试验组一致。')+'</div><small>方案未固定厂家、品牌型号或支架具体长度，请按实际器械记录。下方确认“按方案完成”后才记录为实际操作。</small></div>'}
function applyProcedureConfirmation(){const form=$('moduleForm'),mode=form.elements.namedItem('conforms').value,plan=procedurePlan(current.allocation?.arm);if(mode==='是'&&!plan){form.elements.namedItem('conforms').value='';status('请先完成中央随机化，再确认按组别方案完成。',true);return}for(const key of ['actual','diameter','release','clip','clipCount','clipType','clipModel']){const e=form.elements.namedItem(key);if(mode==='是'&&plan&&Object.hasOwn(plan,key)){e.value=plan[key];e.disabled=true}else e.disabled=key==='clipModel'?false:mode!=='否'}}
function collect(){const form=$('moduleForm');return Object.fromEntries(m().fields.map(f=>[f.id,form?.elements.namedItem(f.id)?.value??rec()?.data[f.id]??'']))}
function safeLeave(){if(busy){status('正在保存或随机化，请等待本次操作完成。');return false}return !dirty||confirm('当前模块有未保存内容。离开前可先点击“保存本页”。仍要切换吗？（恢复草稿会保留）')}
function nav(){ $('nav').innerHTML='<small class="nav-heading">按访视时间填写</small>'+WORKFLOW.map((x,i)=>(x.event&&!WORKFLOW[i-1]?.event?'<small class="nav-heading">发生事件时填写（任何时间）</small>':'')+'<button data-view="'+x.id+'" class="'+(x.id===viewId?'active':'')+'">'+escapeHtml(x.title)+(x.id==='surgery'?' <span class="tag">'+allocationLabel(current?.allocation)+'</span>':'')+'</button>').join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>switchPane(b.dataset.view))}
function info(){if(!current)return;$('identity').textContent='住院号 '+current.patient.id+' ｜ '+CENTERS[current.patient.center];let banner=$('allocationBanner');if(!banner){banner=document.createElement('section');banner.id='allocationBanner';banner.className='result';banner.setAttribute('aria-live','polite');banner.tabIndex=-1;$('identity').closest('.action-strip').after(banner)}const a=current.allocation;banner.innerHTML='<strong>'+(a?'已分组：'+(a.arm==='A'?'试验组':'对照组'):'尚未分组')+'</strong><div class="allocation-grid">'+[['随机号',a?.randomNo],['受试者编号',a?.subjectNo],['随机分组结果',a?(a.arm==='A'?'A · 试验组':'B · 对照组'):null],['对应治疗',a?(a.arm==='A'?'夹锚定全覆膜金属支架（FCSEMS）':'非覆膜金属支架（UCSEMS），无夹锚定'):null]].map(([label,value])=>'<div><span>'+label+'</span><div class="generated">'+escapeHtml(value||'待随机分组后自动生成')+'</div></div>').join('')+'</div>'+(a?'<p class="hint">随机结果已锁定，不会因刷新或重复点击改变。</p>':'<p class="hint">完成入组核对及术中导丝确认后，点击“确认并随机分组”。</p>')}
function input(f,data,locked){const contextFixed=Boolean(activePane().context&&((moduleId==='qol'||moduleId==='clinical')&&f.id==='time'&&data.time===activePane().context||moduleId==='therapy'&&f.id==='visit'&&data.visit===activePane().context));const id='field-'+f.id,val=data[f.id]??'',fixed=moduleId==='procedure'&&['actual','diameter','release','clip','clipCount','clipType'].includes(f.id)&&data.conforms!=='否'||moduleId==='procedure'&&f.id==='clipModel'&&current.allocation?.arm==='B'&&data.conforms==='是',base=`id="${id}" name="${f.id}" ${locked||fixed||contextFixed?'disabled':''}`;let control=f.type==='select'?`<select ${base}><option value="">请选择 / 尚未采集</option>${f.options.map(x=>`<option value="${escapeHtml(x)}" ${val===x?'selected':''}>${escapeHtml(f.id==='stratum'?(x==='P'?'胰腺癌（P）':'非胰腺癌（NP）'):x)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea ${base}>${escapeHtml(val)}</textarea>`:`<input ${base} type="${f.type}" value="${escapeHtml(val)}" ${f.type==='number'?`step="${f.integer?'1':'any'}" min="${f.min??0}" ${f.max!=null?'max="'+f.max+'"':''}`:''}>`;return `<div ${f.type==='textarea'?'class="full"':''} data-field="${f.id}"><label for="${id}">${escapeHtml(f.label)}</label>${control}${detailedGuidance(f)}</div>`}
function schedule(){const date=current?.records.find(r=>r.module==='procedure')?.data.date;if(!m().day&&!m().month)return '';if(!date)return '<div class="datebox">保存支架置入日期后，自动显示计划随访日和窗口。</div>';const target=m().day?addDays(date,m().day):addMonths(date,m().month),window=m().window;return `<div class="datebox">计划日期：<strong>${target}</strong>${window?` ｜ 允许窗口 ${addDays(target,-window)} 至 ${addDays(target,window)}`:'（置入后第180天）'}${moduleId==='month6'?`<br>主要终点第180天：${addDays(date,180)}，与6个日历月分别记录。`:''}<div id="windowCheck" class="hint"></div></div>`}
function randomInfo(){return (current.allocation?'':'<p class="notice">基线表可以稍后补录。本页确认入组资格、导丝通过及肿瘤分层后，即可随机分组；不要求先录完年龄、ECOG或化验。入组事实必须已经核实，不能以未填表代替尚未核实。</p><div id="eligibilityCheck" class="hint"></div><div id="randomSteps"></div>')+randomMethodHelp()}
function render(){nav();info();if(!current){$('module').innerHTML='<h2>先打开一位患者</h2><p class="empty">先选择已有患者，或点击“新建患者”。需要立即随机时可直接进入“随机分组与手术”。</p>';return}const existing=rec(),locked=Boolean(current.allocation&&moduleId==='random');let data={...(moduleId==='random'?randomDefaults():{}),...(existing?existing.data:paneDefaults(activePane()))},draft=null;if(moduleId==='screen')data.eligibility=qualification(data);try{draft=JSON.parse(localStorage.getItem(draftKey())||'null')}catch{}let restore=draft&&!locked&&JSON.stringify(draft.data)!==JSON.stringify(data);if(restore){data=draft.data;if(moduleId==='screen')data.eligibility=qualification(data);dirty=true}
$('module').innerHTML=`${tabs()}<div class="module-head"><h2>${escapeHtml(paneTitle())}</h2></div>${restore?'<div class="notice">已恢复本浏览器未保存输入，请核对后保存到服务器。</div>':''}${m().repeat?`<div class="recordbar"><select aria-label="此模块不同日期的记录" id="recordSelect"><option value="${slot}">${existing?'当前：'+(existing.data.date||'未填日期'):'新记录（未保存）'}</option>${matchingRecords().filter(x=>x.slot!==slot).map(x=>`<option value="${x.slot}">${escapeHtml(x.data.date||'未填日期')} ${escapeHtml(x.data.time||x.data.event||'')}</option>`).join('')}</select><button id="newRecord">＋ 新增一条记录</button></div>`:''}${['therapy','qol','clinical'].includes(moduleId)?legacyTherapy():''}${moduleId==='clinical'?'<p class="notice">仅记录常规诊疗中已经取得的检验，不要求在7、21、28天额外抽血。方案规定满足任一相应生化时限条件，且无胆道症状、无需再次干预，可作为临床成功依据；14天资料在14天随访中记录，不必重复填。</p>':''}${moduleId==='qol'?'<p class="notice">这是本次访视的生活质量记录，不是额外一次随访。使用原始量表，填写完成情况及归档位置。</p>':''}${['screen','baseline'].includes(moduleId)&&current.allocation?'<p class="hint">可补录实际资料；原随机组别及当时的资格确认保持不变。</p>':''}${moduleId==='procedure'?procedureRequirements():''}${schedule()}${moduleId==='random'?randomInfo():''}${moduleId==='procedure'?`<div class="result">随机分配：${escapeHtml(current.allocation?.treatment||'尚未随机化，请先完成中央随机化模块')}<p class="hint">实际操作请如实记录；随机组别与实际治疗分别保存。</p></div>`:''}${moduleId==='month1'?'<p class="notice">30天并发症独立核对；若本次随访早于第30天，请在观察期结束后补全，勿提前填“无”。</p>':''}${locked?'<p class="notice">随机化依据已锁定，只读显示。</p>':''}<form id="moduleForm" novalidate><div class="fields">${m().fields.filter(f=>fieldVisible(moduleId,f.id,activePane().context)).map(f=>input(f,data,locked)).join('')}</div></form><p class="result" id="derived" ${['week2','clinical'].includes(moduleId)?'':'hidden'}></p><div id="checks" class="hint"></div><div class="module-actions">${moduleId==='random'&&!current.allocation?'<button type="button" class="primary" id="randomize">确认并随机分组</button>':''}${moduleId!=='random'?`<button id="saveModule" class="primary" ${locked?'disabled':''}>保存本页</button>`:''}<span id="dirty" class="${dirty?'dirty':'saved'}">${dirty?'有未保存内容':moduleId==='random'&&!current.allocation?(existing?'资料已保存 · 尚未分组':'待填写 · 尚未分组'):existing?'本页资料已保存':'待填写'}</span></div>`;
$('moduleForm').onsubmit=e=>e.preventDefault();$('module').querySelectorAll('[data-pane]').forEach(b=>b.onclick=()=>switchPane(viewId,Number(b.dataset.pane)));if($('legacyTherapy'))$('legacyTherapy').onchange=e=>{if(!e.target.value)return;if(!safeLeave()){e.target.value='';return}slot=e.target.value;dirty=false;render()};$('moduleForm').addEventListener('input',event=>{if(moduleId==='procedure'&&event.target.name==='conforms')applyProcedureConfirmation();dirty=true;$('dirty').textContent='有未保存内容';$('dirty').className='dirty';try{localStorage.setItem(draftKey(),JSON.stringify({data:collect(),version:rec()?.version||0,at:new Date().toISOString()}))}catch{status('浏览器草稿空间不足，请及时保存到服务器',true)}computed()});if($('saveModule'))$('saveModule').onclick=saveModule;if($('randomize'))$('randomize').onclick=randomize;if($('newRecord'))$('newRecord').onclick=()=>{if(!safeLeave())return;slot=crypto.randomUUID();dirty=false;render()};if($('recordSelect'))$('recordSelect').onchange=e=>{if(!safeLeave()){e.target.value=slot;return}slot=e.target.value;dirty=false;render()};computed()}
function computed(){const data=collect();$('derived').textContent=derived(moduleId,data,current.records);const procedure=current.records.find(r=>r.module==='procedure')?.data||{};let warnings=[];if($('windowCheck')&&data.date&&procedure.date){const target=m().day?addDays(procedure.date,m().day):addMonths(procedure.date,m().month);$('windowCheck').textContent=m().window&&(data.date<addDays(target,-m().window)||data.date>addDays(target,m().window))?'实际日期在窗口外：可如实记录，请补充原因。':'实际日期已填写。'}if(moduleId==='procedure'){if(data.diameter&&+data.diameter!==10)warnings.push('直径与方案10mm不一致');if(current.allocation?.arm==='A'&&(data.clip!=='是'||(data.clipCount&&+data.clipCount!==2)))warnings.push('试验组方案为2枚夹锚定');if(current.allocation?.arm==='B'&&data.clip==='是')warnings.push('对照组不实施夹锚定');if(data.exposure&&(+data.exposure<5||+data.exposure>10))warnings.push('外露长度超出方案约5–10mm');}if(moduleId==='baseline'&&data.date&&procedure.date&&(data.date<addDays(procedure.date,-7)||data.date>procedure.date))warnings.push('术前检验日期不在术前7天内');if(moduleId==='ae'&&data.sae&&data.sae!=='否'&&(!data.reported||data.reported==='不适用'||!data.reportedAt))warnings.push('SAE需填写上报情况和时间；方案要求获知后24小时内上报');if(moduleId==='ae'&&data.severity==='致死'&&data.sae==='否')warnings.push('致死事件与“非SAE”冲突，请核对');if(moduleId==='month1'&&data.reviewDate&&procedure.date&&data.reviewDate<addDays(procedure.date,30))warnings.push('尚未完成完整30天观察');if(data.suspectedRbo==='是')warnings.push('请增加RBO事件记录');if(data.ae==='有')warnings.push('请增加AE/SAE记录');$('checks').textContent=warnings.length?'核对提示：'+warnings.join('；'):'';if(moduleId==='random'&&!current.allocation){const errors=eligibility(liveEligibility());$('eligibilityCheck').textContent=errors.length?'待完成：'+errors.join('；'):'入组核对通过，可以随机分组。';if($('randomize'))$('randomize').disabled=busy;$('randomSteps').innerHTML=errors.length?'<button type="button" data-jump="screen">核对入院筛选</button> <button type="button" data-jump="baseline">核对术前资料</button>':'';$('randomSteps').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>switchPane(b.dataset.jump))}for(const f of m().fields.filter(f=>f.when)){const el=$('moduleForm').querySelector('[data-field="'+f.id+'"]');if(el)el.hidden=data[f.when[0]]!==f.when[1]&&!data[f.id]}}
async function saveModule(options={}){if(busy)return false;const data=collect(),errors=validate(moduleId,data);if(errors.length){status(errors.join('；'),true);return false}const id=current.patient.id,key=draftKey(),module=m(),selectedSlot=slot,version=rec()?.version||0;setBusy(true);try{const response=await api('patients/'+encodeURIComponent(id)+'/records','POST',{module:module.id,slot:selectedSlot,data,version});current=response;try{localStorage.removeItem(key)}catch{}dirty=false;render();if(!options.silent)status(module.id==='random'&&!current.allocation?'随机化资料已保存，但尚未分组。请点击“确认并随机分组”。':'保存成功：'+module.title+'。');return true}catch(e){status(e.message,true);return false}finally{setBusy(false)}}
async function randomize(){if(busy||current.allocation)return;const errors=eligibility(liveEligibility());if(errors.length)return status(errors.join('；'),true);if(!confirm('确认已核实入组资格且导丝成功跨越狭窄？系统将保存本页并正式分组；成功后不能重抽。'))return;if(dirty||!rec()){if(!await saveModule({silent:true}))return}const id=current.patient.id;setBusy(true);try{current=await api('patients/'+encodeURIComponent(id)+'/randomize','POST',{});dirty=false;render();status('随机化成功：'+current.allocation.randomNo+' ｜ '+current.allocation.treatment);$('allocationBanner').focus();$('allocationBanner').scrollIntoView({block:'center',behavior:'smooth'})}catch(e){status(e.message+'。结果不明确时可刷新核对，同一患者再次请求不会重新分组。',true)}finally{setBusy(false)}}
function rowRecord(data,module,slot,state){return {module,slot,data,state}}
function download(content,type,name){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);status('已发起下载：'+name+'。请查看浏览器下载记录；若选择保存位置，以你选择的目录为准。')}
function csvSafe(v){let s=String(v??'');if(/^[=+\-@\t\r\n]/.test(s)||/^0\d+$/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function downloadCsv(records,suffix,context=current){const p=context.patient,a=context.allocation;const rows=[['住院号','中心代码','中心名称','随机号','随机组别','受试者编号','随机锁定时间','随机执行人','模块','记录ID','实际日期','字段代码','字段名称','值','保存状态']];for(const r of records)for(const f of r.module.fields)rows.push([p.id,p.center,CENTERS[p.center],a?.randomNo||'',a?.treatment||'',a?.subjectNo||'',a?.at||'',a?.operator||'',r.module.title,r.slot,r.data.date||'',f.id,f.label,f.id==='eligibility'?qualification(r.data):r.data[f.id]??'',r.state]);download('\ufeff'+rows.map(r=>r.map(csvSafe).join(',')).join('\r\n'),'text/csv;charset=utf-8',`MDBO_${p.id}_${suffix}_${new Date().toISOString().slice(0,10)}.csv`)}
async function fresh(){if(!current)throw Error('请先选择患者');return api('patients/'+encodeURIComponent(current.patient.id))}
$('downloadAll').onclick=async()=>{try{const p=await fresh();downloadCsv(p.records.map(r=>rowRecord(r.data,MODULES.find(m=>m.id===r.module),r.slot,'已保存 v'+r.version)),'全部记录',p);if(dirty)status('已下载服务器保存版本；当前模块仍有未保存内容，请先保存后再下载全部记录。')}catch(e){status(e.message,true)}};
async function list(){const r=await api('patients');$('patientSelect').innerHTML='<option value="">选择已保存患者</option>'+r.patients.map(x=>`<option value="${escapeHtml(x.id)}">${escapeHtml(x.id)} · ${escapeHtml(x.center)}</option>`).join('');$('storage').textContent='已连接 · 服务器保存';return r}
$('patientSelect').onchange=async e=>{if(!safeLeave()){e.target.value=current?.patient.id||'';return}if(!e.target.value)return;try{current=await api('patients/'+encodeURIComponent(e.target.value));moduleId='screen';viewId='screen';paneIndex=0;slot='main';dirty=false;render();status('已读取服务器记录')}catch(e){status(e.message,true)}};
$('create').onclick=async()=>{if(!safeLeave())return;const id=$('hospital').value.trim(),center=$('center').value;if(!id)return status('请填写住院号',true);try{current=await api('patients','POST',{id,center});await list();$('patientSelect').value=id;$('newPatient').open=false;$('hospital').value='';moduleId='screen';viewId='screen';paneIndex=0;slot='main';dirty=false;render();status('患者档案已建立。请填写筛选与知情同意。')}catch(e){status(e.message,true)}};
$('center').innerHTML=Object.entries(CENTERS).map(([k,v])=>`<option value="${k}">${k} · ${v}</option>`).join('');window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});render();list().then(()=>status('服务器连接成功。请选择患者或建立新档案。')).catch(e=>{status(e.message,true);$('storage').textContent='未连接 · 尚未保存';$('patientSelect').innerHTML='<option value="">连接失败，请刷新重试</option>'});
function randomDefaults(){const a=current?.records.find(r=>r.module==='screen')?.data||{},b=current?.records.find(r=>r.module==='baseline')?.data||{};return {eligibility:qualification(a),stratum:b.tumor?(b.tumor==='胰腺癌'?'P':'NP'):''};}
