const ECOG_HELP=`<details class="field-help"><summary>评分备注：展开查看 ECOG 0–5分</summary><ol start="0"><li>活动完全正常，日常活动及工作不受限制。</li><li>剧烈体力活动受限；仍可行走，能做轻体力或坐位工作。</li><li>能够行走、生活完全自理，但不能工作；清醒时间超过一半可离床活动。</li><li>只能部分生活自理；清醒时间超过一半在床上或椅上。</li><li>完全不能自理，全部时间卧床或坐椅。</li><li>死亡。</li></ol><p>区分2分与3分，重点核对自理能力和“清醒时间”的活动比例，不是全天24小时。入组仅允许0–2分；如为3–4分，应在筛选中记录不符合，不得改填成2分。</p><small>依据 <a href="https://ecog-acrin.org/resources/ecog-performance-status/" target="_blank" rel="noopener">ECOG-ACRIN 官方评分</a>（Oken等，1982）；中文为填写辅助说明。</small></details>`;
const TNM_HELP=`<details class="field-help"><summary>分期备注：展开查看 TNM 填写方法与癌种差异</summary><p>先确定原发肿瘤，再核对报告采用的分期版本。T表示原发灶范围，N表示区域淋巴结，M表示远处转移；TX/NX为无法评估，不等于T0/N0。N0无区域淋巴结转移；M0无远处转移、M1有远处转移。Ⅰ–Ⅳ期必须查对应癌种的分期组合，不能把T、N、M数字相加。</p><p>建议按报告填写“cT…N…M…，…期；AJCC/UICC第…版；报告日期/编号”。c为临床分期，p为病理分期，yp为新辅助治疗后病理分期。不清楚时注明待核实；未手术者不要凭影像推测病理浸润深度或阳性淋巴结个数。</p><p><strong>以下为AJCC第8版常见定义的核对摘要，不代表方案强制版本，也不自动产生患者分期。其他版本、组织学类型和特殊情况以正式报告及相应标准为准。</strong></p>
<details><summary>胰腺癌（外分泌癌）</summary><p>T1最大径≤2cm；T2＞2至4cm；T3＞4cm；T4侵犯腹腔干、肠系膜上动脉或肝总动脉，不论大小。N1为1–3枚区域淋巴结转移，N2为≥4枚。</p><p>M0时：IA=T1N0，IB=T2N0，IIA=T3N0，IIB=T1–3N1，III=T1–3N2或T4任何N；M1为IV。</p><a href="https://www.cancer.gov/types/pancreatic/hp/pancreatic-treatment-pdq" target="_blank" rel="noopener">NCI：胰腺癌分期原表</a></details>
<details><summary>远端胆管癌</summary><p>T按浸润深度，而非肿块直径：T1＜5mm，T2为5–12mm，T3＞12mm；T4侵犯腹腔干、肠系膜上动脉或肝总动脉。N1为1–3枚，N2为≥4枚区域淋巴结转移。</p><p>M0时：I=T1N0；IIA=T1N1或T2N0；IIB=T2N1或T3N0–1；IIIA=T1–3N2；IIIB=T4任何N；M1为IV。没有病理深度时不要自行套用毫米阈值。</p><a href="https://www.cancer.gov/types/liver/hp/bile-duct-treatment-pdq" target="_blank" rel="noopener">NCI：远端胆管癌分期原表</a></details>
<details><summary>壶腹癌</summary><p>T1a局限于壶腹或Oddi括约肌；T1b超出括约肌或侵入十二指肠黏膜下层；T2侵犯十二指肠固有肌层；T3a侵入胰腺≤0.5cm；T3b侵入胰腺＞0.5cm或胰周/十二指肠周组织、十二指肠浆膜但无T4血管侵犯；T4侵犯腹腔干、肠系膜上动脉或肝总动脉。N1为1–3枚、N2为≥4枚区域淋巴结转移。</p><p>总分期请核对原报告对应分期表；不可直接套用胰腺癌表。该摘要不适用于高分化神经内分泌肿瘤。</p><a href="https://www.cap.org/wp-content/uploads/documents/New-Cancer-Protocols-June-2025/Ampulla_4.3.0.0.REL_CAPCP.pdf?download=true" target="_blank" rel="noopener">CAP：壶腹癌AJCC8定义</a></details>
<details><summary>胆囊癌</summary><p>T1侵入固有层或肌层；T2a侵入腹膜侧肌周结缔组织但未累及浆膜，T2b侵入肝侧肌周结缔组织但未入肝；T3穿透浆膜或直接侵入肝及/或一个邻近器官；T4侵犯门静脉主干、肝动脉或至少两个肝外器官。N1为1–3枚、N2为≥4枚区域淋巴结转移。</p><p>M0时：I=T1N0；IIA=T2aN0；IIB=T2bN0；IIIA=T3N0；IIIB=T1–3N1；IVA=T4N0–1；IVB为任何T、N2，或M1。</p><a href="https://www.cancer.gov/types/gallbladder/hp/gallbladder-treatment-pdq" target="_blank" rel="noopener">NCI：胆囊癌分期原表</a></details>
<p>转移性淋巴结压迫、其他恶性肿瘤：按原发癌种分期，注明原发部位，不使用胆管癌分期替代。该备注供记录核对，最终分期由主管医师确认。</p></details>`;
function fieldHelp(id){return moduleId==='baseline'?(id==='ecog'?ECOG_HELP:id==='tnm'?TNM_HELP:''):'';}
function randomMethodHelp(){return `<details><summary>随机化怎么做？竞争入组与区组有什么区别？</summary><p><strong>本系统以你确认已获批的Excel动态最小化随机为准，不采用固定区组随机。</strong>研究方案旧版的分层区组描述与Excel不同，研究归档时应保留获批修订依据；此处不生成区组号或伪造区组序列。</p><p>竞争入组：各中心不预先分配固定病例名额；符合资格、导丝成功跨越狭窄后，由中央系统逐例受理正式申请。总目标272例、两组各最多136例。并发申请由数据库逐笔确认，不能由中心挑选组别。</p><p>动态最小化：分别假设本例分入A或B，计算总体、所在中心、肿瘤层（胰腺癌P/非胰腺癌NP）的两组人数差绝对值之和，三项权重均为1。以80%概率分入使不平衡较小的一组，20%分入另一组；平分时各50%。某组达到136例后分入另一组；达到272例停止。</p><p>区组随机则按预先生成的区组序列分配，与上述方法不同。本系统没有区组大小或区组编号。随机号按成功分配顺序自动生成，不等于组别。</p><p>A＝试验组：夹锚定全覆膜金属支架；B＝对照组：非覆膜金属支架、无夹锚定。只有点击正式分组并收到成功结果，才算完成随机化。单独保存本页不分组；分组后不能重抽。</p></details>`;}
