export const YN=['是','否'];
export const CENTERS={C01:'大连医科大学附属第二医院',C02:'山东省立第三医院',C03:'吉林大学第一医院',C04:'哈尔滨医科大学附属第二医院',C05:'青海大学附属医院',C06:'宁夏医科大学总医院'};
export const TUMORS=['胰腺癌','远端胆管癌','壶腹癌','胆囊癌','转移性淋巴结压迫','其他符合方案的恶性肿瘤'];
export const GROUPS={A:'试验组 · 夹锚定全覆膜金属支架（FCSEMS）',B:'对照组 · 非覆膜金属支架（UCSEMS，无夹锚定）'};
const f=(id,label,type='text',extra={})=>({id,label,type,...extra});
const s=(id,label,options=YN,extra={})=>f(id,label,'select',{options,...extra});
const n=(id,label,extra={})=>f(id,label,'number',{min:0,...extra});
const d=(id,label='实际记录日期',extra={})=>f(id,label,'date',extra);
const notes=()=>f('notes','补充说明 / 其他选项说明','textarea');
const labs=()=>[n('tbil','TBIL（μmol/L）'),n('alp','ALP（U/L）'),n('alt','ALT（U/L）'),n('ast','AST（U/L）')];
export const INCLUSION=['年龄≥18岁','恶性肿瘤经细胞学、病理学或典型影像学临床表现确诊','影像学证实远端梗阻且距肝门汇合处≥2cm','症状性梗阻性黄疸','无法根治切除或不能耐受手术，拟内镜姑息引流','ECOG 0–2分','能够理解并签署书面知情同意'];
export const EXCLUSION=['肝门部胆管梗阻','内镜无法到达乳头或ERCP无法施行','既往胆道金属支架植入史','凝血异常经纠正仍不满足要求（INR>1.5或血小板<50×10⁹/L）','预计生存期<3个月','严重心肺功能不全不能耐受ERCP','妊娠或哺乳期'];
const follow=()=>[d('date','实际随访日期',{required:true}),s('mode','随访方式',['门诊','电话','住院']),s('symptom','临床症状',['无','黄疸','发热/寒战','腹痛','其他']),...labs(),s('imaging','影像学检查',['无','CT','MRI/MRCP','超声','其他']),s('stent','支架位置',['正常','可疑移位','明确移位']),s('suspectedRbo','是否疑似RBO'),s('anti','抗肿瘤治疗',['无','化疗','放疗','靶向/免疫治疗','其他']),s('ae','自上次访视起不良事件',['无','有']),s('survival','生存状态',['存活','死亡']),d('deathDate','死亡日期',{when:['survival','死亡']}),f('deathCause','死亡原因','text',{when:['survival','死亡']}),notes()];
export const MODULES=[
{id:'screen',title:'入院 · 筛选与知情同意',source:'CRF-01；方案第8–9页',fields:[d('admissionDate','入院日期'),d('date','筛选日期',{required:true}),f('initials','姓名拼音首字母（可留空）'),n('age','年龄（岁）',{integer:true,min:0,max:120,required:true}),s('sex','性别',['男','女']),s('consent','已签署知情同意',YN,{required:true}),d('consentDate','知情同意日期'),s('eligibility','纳入 / 排除标准核对',['符合全部纳入标准，且无任何排除标准','不符合','待核实'],{required:true,hint:'综合核对后选择一次即可；下方可展开查看完整标准。'}),notes()]},
{id:'baseline',title:'术前 · 基线资料',source:'CRF-02',fields:[d('date','实验室检查日期（术前7天内）'),s('ecog','ECOG评分',['0','1','2'],{required:true}),s('tumor','原发肿瘤类型',TUMORS,{required:true}),f('tnm','TNM分期（如适用）'),n('distance','梗阻距肝门汇合处（cm）'),s('drain','既往胆道引流史',['无','塑料支架','鼻胆管','其他']),...labs(),n('wbc','WBC（×10⁹/L）'),n('platelets','血小板（×10⁹/L）'),n('inr','INR'),n('creatinine','肌酐（μmol/L）'),n('ca199','CA19-9（U/mL）'),notes()]},
{id:'random',title:'术中 · 中央随机化',source:'方案第9页；Excel中央随机化登记',fields:[d('date','ERCP日期',{required:true}),s('guidewire','导丝已成功跨越狭窄',YN,{required:true}),f('operator','随机执行人姓名','text',{required:true}),notes()]},
{id:'procedure',title:'手术 · ERCP / 支架 / 夹锚定',source:'CRF-03/04；方案第9页',fields:[s('conforms','是否按随机组方案完成',YN,{hint:'选是后，固定操作项目自动记录；选否则展开实际操作，填写偏离原因。'}),d('date','支架置入日期',{required:true}),s('anesthesia','镇静/麻醉方式',['镇静','全麻','其他']),s('est','EST/ESBD',['EST','ESBD','均未做']),s('nasal','是否置入鼻胆管'),n('stenosis','狭窄段长度（cm）'),s('actual','实际置入治疗',['夹锚定FCSEMS','UCSEMS','其他','未置入']),f('stentModel','支架厂家 / 型号'),n('diameter','实际支架直径（mm）',{hint:'方案要求10mm；如有偏离请如实记录。'}),n('length','支架长度（mm）'),s('release','支架释放方式',['跨乳头放置','其他']),s('technical','技术成功（覆盖狭窄全长且透视位置理想）'),s('complication','术中并发症',['无','出血','穿孔','其他']),s('clip','是否实施夹锚定',['是','否','NA']),f('clipType','夹子类型（方案）'),f('clipModel','夹子品牌 / 型号'),n('clipCount','实际夹数量（枚）',{integer:true,hint:'试验组方案为2枚；对照组不锚定。'}),n('exposure','远端外露长度（mm）',{hint:'方案约5–10mm'}),f('deviation','方案偏离原因 / 夹锚定备注','textarea'),notes()]},
{id:'ae',title:'不良事件及严重不良事件',repeat:true,source:'CRF-08；方案第11页',fields:[d('date','发生日期',{required:true}),f('event','事件名称','text',{required:true}),s('severity','严重程度',['轻','中','重','致死']),s('sae','是否SAE',['否','是-死亡','是-危及生命','是-住院/延长住院','是-致残','是-其他']),s('related','与器械/操作相关性',['无关','可能相关','很可能相关','肯定相关']),s('measure','处理措施',['对症','抗生素','输血','内镜处理','外科/介入','其他']),s('outcome','转归',['痊愈','好转','未愈','后遗症','死亡']),f('awareAt','获知时间','datetime-local'),s('reported','上报情况',['不适用','24h内上报PI/DSMB/伦理','其他']),f('reportedAt','上报时间','datetime-local'),notes()]},
{id:'week2',title:'术后2周 · 14天随访',day:14,window:3,source:'CRF-05',fields:[d('date','实际随访日期',{required:true}),s('mode','随访方式',['门诊','电话','住院']),s('improve','黄疸 / 瘙痒 / 腹痛改善',['明显改善','部分改善','无变化','加重']),d('labDate','TBIL采血日期'),n('tbil','第14天TBIL（μmol/L）'),s('biliarySymptoms','仍有发热等胆道症状'),s('needIntervention','仍需再次干预'),s('combined','合并治疗（如化疗）'),d('combinedDate','合并治疗日期',{when:['combined','是']}),notes()]},
{id:'month1',title:'术后1个月 · 随访与30天并发症',month:1,window:7,source:'CRF-06；CRF-05的30天事件移至此处',fields:[...follow(),d('reviewDate','30天事件观察截止日期'),s('pancreatitis','30天内胰腺炎',['无','轻','中','重']),s('cholecystitis','30天内胆囊炎',['无','轻','中','重']),s('bleeding','30天内出血',['无','轻','中','重']),s('migration','30天内支架移位',['无','有']),s('migrationIntervention','支架移位需干预',YN,{when:['migration','有']})]},
{id:'month3',title:'术后3个月 · 定期随访',month:3,window:7,source:'CRF-06',fields:follow()},
{id:'month6',title:'术后6个月 · 随访',month:6,window:7,source:'CRF-06（180天主要终点单独标注）',fields:follow()},
{id:'month12',title:'术后12个月 · 定期随访',month:12,window:7,source:'CRF-06',fields:follow()},
{id:'rbo',title:'再次胆道梗阻与处理',repeat:true,source:'CRF-07；由事件裁定委员会最终裁定',fields:[d('date','疑似RBO触发日期',{required:true}),s('confirmed','RBO最终裁定'),d('rboDate','裁定RBO发生日期'),f('adjudicator','裁定人 / 委员会'),s('type','RBO类型',['支架闭塞','有症状支架移位','其他']),s('occlusion','闭塞原因',['肿瘤内生','末端过度生长','胆泥/食物嵌塞','血凝块','其他']),s('migration','移位情况',['部分-近端','部分-远端','完全-近端','完全-远端','NA']),s('clip','夹在位',['是','否','NA']),s('intervention','再干预方式',['ERCP清洗','置入塑料支架','套叠金属支架','更换支架','外科/介入','其他']),d('interventionDate','再干预日期'),s('technical','再干预技术成功'),s('ae','再干预并发症',['无','有']),notes()]},
{id:'qol',title:'生活质量评估',repeat:true,source:'CRF-09；记录原量表结果，不凭空生成条目或计分',fields:[d('date','实际评估日期',{required:true}),s('time','评估时间点',['基线','3月','6月']),s('scale','量表类型',['QLQ-C30','QLQ-BIL21','两者']),s('method','填写方式',['自填','访谈','代填']),s('complete','是否完整'),n('missing','缺失条目数',{integer:true}),f('proxy','代填说明'),f('sourceRef','原始量表文件编号 / 归档位置'),notes()]},
{id:'therapy',title:'用药与抗肿瘤治疗',repeat:true,source:'CRF-10',fields:[s('visit','所属访视',['入院','术前','围术期','术后7–30天','术后3个月','术后6个月','术后12个月'],{hint:'新记录按当前访视自动带入。历史记录可核对后手动归属，不改变实际用药日期。'}),d('date','记录日期',{required:true}),s('nsaid','围术期NSAIDs',['未用','吲哚美辛','双氯芬酸','其他']),f('nsaidOther','NSAIDs其他说明'),s('pancreaticStent','预防性胰管支架'),f('spec','胰管支架规格'),s('antibiotic','围术期抗生素'),f('antibioticDetail','抗生素药物 / 疗程'),f('chemo','化疗方案'),d('chemoStart','化疗开始日期'),d('chemoEnd','化疗结束日期'),s('radiation','放疗'),d('radioStart','放疗开始日期'),d('radioEnd','放疗结束日期'),s('immune','免疫 / 靶向治疗'),f('immuneDrug','免疫 / 靶向药物'),notes()]},
{id:'clinical',title:'术后早期检验与临床成功评价',repeat:true,source:'方案第10页；仅记录已有常规诊疗数据，不新增强制访视',fields:[d('date','采血 / 评价日期',{required:true}),s('time','评价时点',['7天','21天','28天']),n('tbil','TBIL（μmol/L）'),s('biliarySymptoms','仍有发热等胆道症状'),s('needIntervention','仍需再次干预'),notes()]},
{id:'outcome',title:'结局 · 180天 / 退出 / 失访',day:180,source:'CRF-11；竞争风险所需事件日期分别保留',fields:[d('date','评价日期',{required:true}),s('rbo180','截至180天是否发生RBO'),d('rboDate','首次裁定RBO日期'),s('rboType','RBO类型',['支架闭塞','有症状支架移位','其他']),s('exit','退出研究'),s('exitReason','退出原因',['撤回同意','技术失败','根治手术','SAE','失访','其他']),d('exitDate','退出日期'),d('lastFollow','最后一次有效随访日期'),d('surgeryDate','外科根治手术日期'),d('deathDate','死亡日期（如适用）'),s('deathCause','死因',['NA','肿瘤进展','支架相关并发症','其他']),notes()]}
];
export function procedurePlan(arm){if(!['A','B'].includes(arm))return null;return {actual:arm==='A'?'夹锚定FCSEMS':'UCSEMS',diameter:'10',release:'跨乳头放置',clip:arm==='A'?'是':'NA',clipCount:arm==='A'?'2':'0',clipType:arm==='A'?'可重复开闭软组织夹':'NA',...(arm==='B'?{clipModel:'NA'}:{})}}
export function qualification(data){if(Object.hasOwn(data,'eligibility'))return data.eligibility;return INCLUSION.every((_,i)=>data['in'+i]==='是')&&EXCLUSION.every((_,i)=>data['ex'+i]==='否')?'符合全部纳入标准，且无任何排除标准':''}
const HINTS={
screen:{date:'按实际筛选日填写。',age:'方案入组年龄≥18岁。',consent:'签署书面知情同意后方可开始研究相关流程。',consentDate:'不得晚于中央随机化ERCP日期。',initials:'按CRF，可留空；不要求录入患者全名。'},
baseline:{date:'TBIL基线采用术前7天内结果；按检验单记录日期。',ecog:'入组允许0、1或2分；详细评分标准见下方评分备注。',tumor:'按确诊原发肿瘤填写；自动归入胰腺癌P / 非胰腺癌NP层。',tnm:'按原发癌种及报告记录TNM、总分期、版本与依据；展开下方备注核对，不能混用不同癌种标准。',distance:'按影像记录狭窄距肝门汇合处距离；入组要求≥2cm。',drain:'既往金属支架置入属于排除标准；本项如实记录既往引流。',inr:'方案排除：纠正后仍INR>1.5；勿用纠正前结果代替纠正后判断。',platelets:'单位×10⁹/L；方案排除：纠正后仍<50。'},
random:{date:'实际ERCP日期；必须在导丝成功跨越狭窄后申请随机。',guidewire:'选择“是”且资格核对通过后才能分配。',operator:'实际执行中央随机化的人员姓名；分配后固定保留。'},
procedure:{date:'实际支架置入日，是随访、180天终点和TRBO的起算日期。',stenosis:'按术中造影测量，单位cm。',actual:'如实记录实际治疗；不会改变已锁定的随机组。',stentModel:'按备案名称填写厂家和型号。',length:'按实际置入支架记录，单位mm。',release:'方案两组均跨乳头放置；偏离时选择其他并说明。',technical:'成功释放并覆盖狭窄全长，且透视下位置理想。',clip:'试验组夹锚定；对照组不锚定，填NA。',clipModel:'按备案名称填写；对照组可留空。',deviation:'实际治疗、直径、释放方式或夹数量偏离方案时写明原因。'},
ae:{event:'CRF示例：胰腺炎、胆囊炎、出血、穿孔、感染、夹相关损伤。',severity:'事件严重程度与是否SAE分别判断；致死应核对SAE死亡项。',sae:'包括死亡、危及生命、住院/延长住院、致残及其他重要医学事件。',awareAt:'首次获知事件的实际时间，用于核对24小时上报时限。',reported:'SAE在获知后24小时内上报PI、DSMB和伦理委员会。',reportedAt:'实际上报时间；超过24小时也应如实填写。'},
week2:{date:'术后14天，允许访视窗口±3天。',labDate:'真实采血日；访视窗口不等同于临床成功的生化时限。',tbil:'CRF的14天生化标准：较术前基线下降≥50%。',biliarySymptoms:'方案临床成功还要求无发热等胆道症状。',needIntervention:'方案临床成功还要求无需再次干预。'},
rbo:{date:'疑似触发日期与最终裁定RBO日期分别记录。',confirmed:'由事件裁定委员会确认，疑似事件不能直接当作终点。',rboDate:'按委员会裁定填写事件实际发生日期。',type:'按TOKYO 2014：支架闭塞或有症状支架移位；其他需说明。',intervention:'未发生RBO前，方案禁止预防性再次胆道引流。',ae:'如有并发症，同时填写AE/SAE记录。'},
qol:{time:'CRF评估时点：基线、3个月、6个月。',scale:'使用授权原始QLQ-C30 / QLQ-BIL21量表；这里记录完成情况。',missing:'实际缺失条目数；不可把缺失数据填为0分。',proxy:'代填时说明原因及代填情况。'},
therapy:{nsaid:'按实际围术期用药选择；其他药物填写说明。',antibioticDetail:'写明药物名称及疗程。',chemo:'方案名称，并分别记录起止日期。',immuneDrug:'如实记录药名，不自动推断是否接受治疗。'},
clinical:{time:'仅补录已有常规诊疗结果，不增加强制访视。',tbil:'方案：7天内下降≥25%，21天内≥75%，或28天内≤2mg/dL（约34.2μmol/L）。'},
outcome:{date:'主要终点评价以支架置入后第180天为准。',rbo180:'仅依据截至180天的已裁定RBO，不能把失访当作未发生。',lastFollow:'最后一次有效随访日期，用于失访删失。',surgeryDate:'未发生RBO前接受根治手术者，在手术日删失。',deathDate:'死亡作为竞争事件独立记录，不自动计为RBO。'}};
for(const module of MODULES)for(const field of module.fields){field.hint=field.hint||HINTS[module.id]?.[field.id]||(['tbil','alp','alt','ast','wbc','creatinine','ca199'].includes(field.id)?'按检验单原值及上方单位填写；未检测请留空。':field.type==='select'&&field.options.includes('其他')?'选择其他时，在本模块补充说明中填写具体情况。':'');if(field.when)field.hint=(field.hint?field.hint+' ':'')+'仅“'+module.fields.find(x=>x.id===field.when[0]).label+'”为“'+field.when[1]+'”时填写。';}
export function addDays(date,days){if(!date)return '';let x=new Date(date+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+days);return x.toISOString().slice(0,10)}
export function addMonths(date,months){if(!date)return '';let x=new Date(date+'T00:00:00Z'),day=x.getUTCDate();x.setUTCDate(1);x.setUTCMonth(x.getUTCMonth()+months);let end=new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0)).getUTCDate();x.setUTCDate(Math.min(day,end));return x.toISOString().slice(0,10)}
export function validate(moduleId,data){const m=MODULES.find(x=>x.id===moduleId);if(!m)throw Error('未知模块');const errors=[];for(const k of Object.keys(data))if(!m.fields.some(f=>f.id===k)&&!(moduleId==='screen'&&/^(in|ex)[0-6]$/.test(k)))errors.push('未知字段：'+k);for(const f of m.fields){const v=data[f.id];if(v===''||v==null)continue;if(typeof v!=='string'||v.length>4000){errors.push(f.label+'格式错误');continue}if(f.type==='select'&&!f.options.includes(v))errors.push(f.label+'请使用规定选项');if(f.type==='number'&&(!Number.isFinite(+v)||+v<(f.min??0)||(f.max!=null&&+v>f.max)||(f.integer&&!Number.isInteger(+v))))errors.push(f.label+'数值不合适');if(f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))errors.push(f.label+'日期无效');}if(data.survival==='存活'&&(data.deathDate||data.deathCause))errors.push('存活状态与死亡资料冲突，请核对');if(moduleId==='ae'&&(data.severity==='致死'||data.outcome==='死亡')&&data.sae&&data.sae!=='是-死亡')errors.push('致死/死亡事件请核对SAE死亡项');for(const [start,end] of [['chemoStart','chemoEnd'],['radioStart','radioEnd'],['awareAt','reportedAt']])if(data[start]&&data[end]&&data[end]<data[start])errors.push('结束/上报时间不能早于开始/获知时间');return errors}
export function eligibility(records){const get=id=>records.find(r=>r.module===id)?.data||{};const a=get('screen'),b=get('baseline'),c=get('random');let errors=[];if(a.consent!=='是'||!a.consentDate)errors.push('知情同意及签署日期未完成');if(!(Number(a.age)>=18))errors.push('年龄须≥18岁');if(qualification(a)!=='符合全部纳入标准，且无任何排除标准')errors.push('请确认符合全部纳入标准且无排除标准');if(!['0','1','2'].includes(b.ecog)||!TUMORS.includes(b.tumor)||!(Number(b.distance)>=2))errors.push('基线肿瘤、ECOG或梗阻距离不完整');if(c.guidewire!=='是'||!c.date||!c.operator?.trim())errors.push('须确认导丝跨越狭窄并填写执行人及ERCP日期');if(a.consentDate&&c.date&&a.consentDate>c.date)errors.push('知情同意不能晚于随机化ERCP日期');return errors}
export function derived(moduleId,data,records){if(!['week2','clinical'].includes(moduleId))return '';const baseline=records.find(x=>x.module==='baseline')?.data||{},procedure=records.find(x=>x.module==='procedure')?.data||{},base=Number(baseline.tbil);if(!baseline.tbil||data.tbil===''||data.tbil==null||base<=0)return '自动计算：尚缺基线或本次TBIL';const pct=(1-Number(data.tbil)/base)*100,limit=moduleId==='week2'?14:data.time==='7天'?7:data.time==='21天'?21:data.time==='28天'?28:null;const threshold=limit===7?25:limit===14?50:limit===21?75:null;const lab=limit===28?Number(data.tbil)<=34.2:threshold!==null&&pct>=threshold;const sample=moduleId==='week2'?data.labDate:data.date;const days=sample&&procedure.date?(Date.parse(sample)-Date.parse(procedure.date))/86400000:null;let result;if(!limit)result='请先选择评价时点';else if(!lab)result='本次生化条件未达到';else if(days===null)result='生化条件达到，尚缺置入日或采血日，无法核实时限';else if(days<0||days>limit)result='生化条件达到，但采血不在方案'+limit+'天内，不能据此判为该时点临床成功';else if(!data.biliarySymptoms||!data.needIntervention)result='生化及时间条件达到，尚缺症状/再干预核对';else if(data.biliarySymptoms==='否'&&data.needIntervention==='否')result='符合本时点方案临床成功条件';else result='不符合本时点临床成功条件（仍有症状或需再干预）';return 'TBIL下降 '+pct.toFixed(1)+'%；'+result;}
