export const YN=['是','否'];
export const CENTERS={C01:'大连医科大学附属第二医院',C02:'山东省立第三医院',C03:'吉林大学第一医院',C04:'哈尔滨医科大学附属第二医院',C05:'青海大学附属医院',C06:'宁夏医科大学总医院'};
export const TUMORS=['胰腺癌','远端胆管癌','壶腹癌','胆囊癌','转移性淋巴结压迫','其他符合方案的恶性肿瘤'];
export const GROUPS={A:'试验组 · 夹锚定全覆膜金属支架（FCSEMS）',B:'对照组 · 非覆膜金属支架（UCSEMS，无夹锚定）'};
const f=(id,label,type='text',extra={})=>({id,label,type,...extra});
const s=(id,label,options=YN,extra={})=>f(id,label,'select',{options,...extra});
const n=(id,label,extra={})=>f(id,label,'number',{min:0,...extra});
const d=(id,label='实际记录日期',extra={})=>f(id,label,'date',extra);
const notes=()=>f('notes','补充说明 / 其他选项说明','textarea');
const labs=()=>[n('tbil','TBIL（μmol/L）'),n('alp','ALP（U/L）'),n('alt','ALT（U/L）'),n('ast','AST（U/L）')];
export const INCLUSION=['年龄≥18岁','恶性肿瘤经细胞学、病理学或典型影像学临床表现确诊','影像学证实远端梗阻且距肝门汇合处≥2cm','症状性梗阻性黄疸','无法根治切除或不能耐受手术，拟内镜姑息引流','ECOG 0–2分','能够理解并签署书面知情同意'];
export const EXCLUSION=['肝门部胆管梗阻','内镜无法到达乳头或ERCP无法施行','既往胆道金属支架植入史','凝血异常经纠正仍不满足要求（INR>1.5或血小板<50×10⁹/L）','预计生存期<3个月','严重心肺功能不全不能耐受ERCP','妊娠或哺乳期'];
const follow=()=>[d('date','实际随访日期',{required:true}),s('mode','随访方式',['门诊','电话','住院']),s('symptom','临床症状',['无','黄疸','发热/寒战','腹痛','其他']),...labs(),s('imaging','影像学检查',['无','CT','MRI/MRCP','超声','其他']),s('stent','支架位置',['正常','可疑移位','明确移位']),s('suspectedRbo','是否疑似RBO'),s('anti','抗肿瘤治疗',['无','化疗','放疗','靶向/免疫治疗','其他']),s('ae','自上次访视起不良事件',['无','有']),s('survival','生存状态',['存活','死亡']),d('deathDate','死亡日期',{when:['survival','死亡']}),f('deathCause','死亡原因','text',{when:['survival','死亡']}),notes()];
export const MODULES=[
{id:'screen',title:'入院 · 筛选与知情同意',source:'CRF-01；方案第8–9页',fields:[d('admissionDate','入院日期'),d('date','筛选日期',{required:true}),f('initials','姓名拼音首字母（可留空）'),n('age','年龄（岁）',{integer:true,min:0,max:120,required:true}),s('sex','性别',['男','女']),s('consent','已签署知情同意',YN,{required:true}),d('consentDate','知情同意日期'),...INCLUSION.map((x,i)=>s('in'+i,'入选'+(i+1)+'：'+x)),...EXCLUSION.map((x,i)=>s('ex'+i,'排除'+(i+1)+'：'+x)),notes()]},
{id:'baseline',title:'术前 · 基线资料',source:'CRF-02',fields:[d('date','实验室检查日期（术前7天内）'),s('ecog','ECOG评分',['0','1','2'],{required:true}),s('tumor','原发肿瘤类型',TUMORS,{required:true}),f('tnm','TNM分期（如适用）'),n('distance','梗阻距肝门汇合处（cm）'),s('drain','既往胆道引流史',['无','塑料支架','鼻胆管','其他']),...labs(),n('wbc','WBC（×10⁹/L）'),n('platelets','血小板（×10⁹/L）'),n('inr','INR'),n('creatinine','肌酐（μmol/L）'),n('ca199','CA19-9（U/mL）'),notes()]},
{id:'random',title:'术中 · 中央随机化',source:'方案第9页；Excel中央随机化登记',fields:[d('date','ERCP日期',{required:true}),s('guidewire','导丝已成功跨越狭窄',YN,{required:true}),f('operator','随机执行人姓名','text',{required:true}),notes()]},
{id:'procedure',title:'手术 · ERCP / 支架 / 夹锚定',source:'CRF-03/04；方案第9页',fields:[d('date','支架置入日期',{required:true}),s('anesthesia','镇静/麻醉方式',['镇静','全麻','其他']),s('est','EST/ESBD',['EST','ESBD','均未做']),s('nasal','是否置入鼻胆管'),n('stenosis','狭窄段长度（cm）'),s('actual','实际置入治疗',['夹锚定FCSEMS','UCSEMS','其他','未置入']),f('stentModel','支架厂家 / 型号'),n('diameter','实际支架直径（mm）',{hint:'方案要求10mm；如有偏离请如实记录。'}),n('length','支架长度（mm）'),s('release','支架释放方式',['跨乳头放置','其他']),s('technical','技术成功（覆盖狭窄全长且透视位置理想）'),s('complication','术中并发症',['无','出血','穿孔','其他']),s('clip','是否实施夹锚定',['是','否','NA']),f('clipModel','夹子品牌 / 型号'),n('clipCount','实际夹数量（枚）',{integer:true,hint:'试验组方案为2枚；对照组不锚定。'}),n('exposure','远端外露长度（mm）',{hint:'方案约5–10mm'}),f('deviation','方案偏离原因 / 夹锚定备注','textarea'),notes()]},
{id:'ae',title:'术后 / 全程 · AE与SAE',repeat:true,source:'CRF-08；方案第11页',fields:[d('date','发生日期',{required:true}),f('event','事件名称','text',{required:true}),s('severity','严重程度',['轻','中','重','致死']),s('sae','是否SAE',['否','是-死亡','是-危及生命','是-住院/延长住院','是-致残','是-其他']),s('related','与器械/操作相关性',['无关','可能相关','很可能相关','肯定相关']),s('measure','处理措施',['对症','抗生素','输血','内镜处理','外科/介入','其他']),s('outcome','转归',['痊愈','好转','未愈','后遗症','死亡']),f('awareAt','获知时间','datetime-local'),s('reported','上报情况',['不适用','24h内上报PI/DSMB/伦理','其他']),f('reportedAt','上报时间','datetime-local'),notes()]},
{id:'week2',title:'术后2周 · 14天随访',day:14,window:3,source:'CRF-05',fields:[d('date','实际随访日期',{required:true}),s('mode','随访方式',['门诊','电话','住院']),s('improve','黄疸 / 瘙痒 / 腹痛改善',['明显改善','部分改善','无变化','加重']),d('labDate','TBIL采血日期'),n('tbil','第14天TBIL（μmol/L）'),s('biliarySymptoms','仍有发热等胆道症状'),s('needIntervention','仍需再次干预'),s('combined','合并治疗（如化疗）'),d('combinedDate','合并治疗日期',{when:['combined','是']}),notes()]},
{id:'month1',title:'术后1个月 · 随访与30天并发症',month:1,window:7,source:'CRF-06；CRF-05的30天事件移至此处',fields:[...follow(),d('reviewDate','30天事件观察截止日期'),s('pancreatitis','30天内胰腺炎',['无','轻','中','重']),s('cholecystitis','30天内胆囊炎',['无','轻','中','重']),s('bleeding','30天内出血',['无','轻','中','重']),s('migration','30天内支架移位',['无','有']),s('migrationIntervention','支架移位需干预',YN,{when:['migration','有']})]},
{id:'month3',title:'术后3个月 · 定期随访',month:3,window:7,source:'CRF-06',fields:follow()},
{id:'month6',title:'术后6个月 · 随访',month:6,window:7,source:'CRF-06（180天主要终点单独标注）',fields:follow()},
{id:'month12',title:'术后12个月 · 定期随访',month:12,window:7,source:'CRF-06',fields:follow()},
{id:'rbo',title:'事件记录 · RBO与再干预',repeat:true,source:'CRF-07；由事件裁定委员会最终裁定',fields:[d('date','疑似RBO触发日期',{required:true}),s('confirmed','RBO最终裁定'),d('rboDate','裁定RBO发生日期'),f('adjudicator','裁定人 / 委员会'),s('type','RBO类型',['支架闭塞','有症状支架移位','其他']),s('occlusion','闭塞原因',['肿瘤内生','末端过度生长','胆泥/食物嵌塞','血凝块','其他']),s('migration','移位情况',['部分-近端','部分-远端','完全-近端','完全-远端','NA']),s('clip','夹在位',['是','否','NA']),s('intervention','再干预方式',['ERCP清洗','置入塑料支架','套叠金属支架','更换支架','外科/介入','其他']),d('interventionDate','再干预日期'),s('technical','再干预技术成功'),s('ae','再干预并发症',['无','有']),notes()]},
{id:'qol',title:'量表 · 基线 / 3月 / 6月',repeat:true,source:'CRF-09；记录原量表结果，不凭空生成条目或计分',fields:[d('date','实际评估日期',{required:true}),s('time','评估时间点',['基线','3月','6月']),s('scale','量表类型',['QLQ-C30','QLQ-BIL21','两者']),s('method','填写方式',['自填','访谈','代填']),s('complete','是否完整'),n('missing','缺失条目数',{integer:true}),f('proxy','代填说明'),f('sourceRef','原始量表文件编号 / 归档位置'),notes()]},
{id:'therapy',title:'全程 · 合并用药 / 抗肿瘤治疗',repeat:true,source:'CRF-10',fields:[d('date','记录日期',{required:true}),s('nsaid','围术期NSAIDs',['未用','吲哚美辛','双氯芬酸','其他']),f('nsaidOther','NSAIDs其他说明'),s('pancreaticStent','预防性胰管支架'),f('spec','胰管支架规格'),s('antibiotic','围术期抗生素'),f('antibioticDetail','抗生素药物 / 疗程'),f('chemo','化疗方案'),d('chemoStart','化疗开始日期'),d('chemoEnd','化疗结束日期'),s('radiation','放疗'),d('radioStart','放疗开始日期'),d('radioEnd','放疗结束日期'),s('immune','免疫 / 靶向治疗'),f('immuneDrug','免疫 / 靶向药物'),notes()]},
{id:'clinical',title:'补充 · 7 / 21 / 28天临床成功依据',repeat:true,source:'方案第10页；仅记录已有常规诊疗数据，不新增强制访视',fields:[d('date','采血 / 评价日期',{required:true}),s('time','评价时点',['7天','21天','28天']),n('tbil','TBIL（μmol/L）'),s('biliarySymptoms','仍有发热等胆道症状'),s('needIntervention','仍需再次干预'),notes()]},
{id:'outcome',title:'结局 · 180天 / 退出 / 失访',day:180,source:'CRF-11；竞争风险所需事件日期分别保留',fields:[d('date','评价日期',{required:true}),s('rbo180','截至180天是否发生RBO'),d('rboDate','首次裁定RBO日期'),s('rboType','RBO类型',['支架闭塞','有症状支架移位','其他']),s('exit','退出研究'),s('exitReason','退出原因',['撤回同意','技术失败','根治手术','SAE','失访','其他']),d('exitDate','退出日期'),d('lastFollow','最后一次有效随访日期'),d('surgeryDate','外科根治手术日期'),d('deathDate','死亡日期（如适用）'),s('deathCause','死因',['NA','肿瘤进展','支架相关并发症','其他']),notes()]}
];
export function addDays(date,days){if(!date)return '';let x=new Date(date+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+days);return x.toISOString().slice(0,10)}
export function addMonths(date,months){if(!date)return '';let x=new Date(date+'T00:00:00Z'),day=x.getUTCDate();x.setUTCDate(1);x.setUTCMonth(x.getUTCMonth()+months);let end=new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0)).getUTCDate();x.setUTCDate(Math.min(day,end));return x.toISOString().slice(0,10)}
export function validate(moduleId,data){const m=MODULES.find(x=>x.id===moduleId);if(!m)throw Error('未知模块');const errors=[];for(const k of Object.keys(data))if(!m.fields.some(f=>f.id===k))errors.push('未知字段：'+k);for(const f of m.fields){const v=data[f.id];if(v===''||v==null)continue;if(typeof v!=='string'||v.length>4000){errors.push(f.label+'格式错误');continue}if(f.type==='select'&&!f.options.includes(v))errors.push(f.label+'请使用规定选项');if(f.type==='number'&&(!Number.isFinite(+v)||+v<(f.min??0)||(f.max!=null&&+v>f.max)||(f.integer&&!Number.isInteger(+v))))errors.push(f.label+'数值不合适');if(f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))errors.push(f.label+'日期无效');}return errors}
export function eligibility(records){const get=id=>records.find(r=>r.module===id)?.data||{};const a=get('screen'),b=get('baseline'),c=get('random');let errors=[];if(a.consent!=='是'||!a.consentDate)errors.push('知情同意及签署日期未完成');if(!(Number(a.age)>=18))errors.push('年龄须≥18岁');INCLUSION.forEach((_,i)=>{if(a['in'+i]!=='是')errors.push('入选'+(i+1)+'未确认')});EXCLUSION.forEach((_,i)=>{if(a['ex'+i]!=='否')errors.push('排除'+(i+1)+'未排除')});if(!['0','1','2'].includes(b.ecog)||!TUMORS.includes(b.tumor)||!(Number(b.distance)>=2))errors.push('基线肿瘤、ECOG或梗阻距离不完整');if(c.guidewire!=='是'||!c.date||!c.operator)errors.push('须确认导丝跨越狭窄并填写执行人及ERCP日期');if(a.consentDate&&c.date&&a.consentDate>c.date)errors.push('知情同意不能晚于随机化ERCP日期');return errors}
export function derived(moduleId,data,records){const baseline=records.find(x=>x.module==='baseline')?.data||{},base=Number(baseline.tbil);if(!['week2','clinical'].includes(moduleId))return '';if(!baseline.tbil||!data.tbil||base<=0)return '自动计算：尚缺基线或本次TBIL';const pct=(1-Number(data.tbil)/base)*100;const threshold=moduleId==='week2'?50:data.time==='7天'?25:data.time==='21天'?75:null;const lab=threshold===null?data.time==='28天'&&Number(data.tbil)<=34.2:pct>=threshold;const status=data.biliarySymptoms==='否'&&data.needIntervention==='否'?(lab?'满足本时点评价条件':'不满足本时点评价条件'):'症状或再干预资料未满足/未完成';return `TBIL下降 ${pct.toFixed(1)}%；${status}（需结合实际采血日核对方案时限）`}
