import { MODULES,CENTERS,GROUPS,eligibility,validate,procedurePlan } from './schema.js';
export function allocationPlan(previous,center,stratum,u){const count=(arm,filter=()=>true)=>previous.filter(r=>r.arm===arm&&filter(r)).length;const a=count('A'),b=count('B');if(a+b>=272)throw Error('已达到272例，停止随机化');const score=(arm)=>Math.abs(a+(arm==='A')-b-(arm==='B'))+Math.abs(count('A',r=>r.center===center)+(arm==='A')-count('B',r=>r.center===center)-(arm==='B'))+Math.abs(count('A',r=>r.stratum===stratum)+(arm==='A')-count('B',r=>r.stratum===stratum)-(arm==='B'));const scoreA=score('A'),scoreB=score('B'),probA=a>=136?0:b>=136?1:scoreA<scoreB?.8:scoreB<scoreA?.2:.5;return {arm:u<probA?'A':'B',scoreA,scoreB,probA,seq:a+b+1};}
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const parseRow=r=>({...r,data:JSON.parse(r.data)});
async function bundle(db,id){const patient=await db.prepare('SELECT * FROM patients WHERE id=?').bind(id).first();if(!patient)return null;const rows=await db.prepare('SELECT * FROM records WHERE patient=? ORDER BY module,slot').bind(id).all();const allocation=await db.prepare('SELECT patient,seq,arm,center,stratum,at,actor,operator FROM allocations WHERE patient=?').bind(id).first();const archived=await db.prepare('SELECT archived_at,actor FROM patient_archives WHERE patient=?').bind(id).first();return {patient,records:rows.results.map(parseRow),archived:archived||null,allocation:allocation?{...allocation,randomNo:'R'+String(allocation.seq).padStart(4,'0'),subjectNo:allocation.center+'-R'+String(allocation.seq).padStart(4,'0'),treatment:GROUPS[allocation.arm]}:null}}
async function body(req){const raw=await req.text();if(raw.length>100000)throw Error('提交内容过长');return JSON.parse(raw)}
export default {async fetch(req,env){try{const url=new URL(req.url);if(!url.pathname.startsWith('/api/'))return new Response(HTML,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}});const user=req.headers.get('oai-authenticated-user-id');if(!user)return json({error:'请先通过网站登录后再保存'},401);const actor=req.headers.get('oai-authenticated-user-email')||user;if(!env.DB)return json({error:'数据库未连接，请勿关闭未保存页面'},503);const db=env.DB;
if(req.method!=='GET'&&req.headers.get('Origin')!==url.origin)return json({error:'请求来源不匹配'},403);
if(url.pathname==='/api/patients'&&req.method==='GET'){const p=await db.prepare('SELECT id,center,created FROM patients WHERE NOT EXISTS(SELECT 1 FROM patient_archives a WHERE a.patient=patients.id) ORDER BY created DESC').all();return json({patients:p.results,user:actor,storage:'服务器数据库'})}
if(url.pathname==='/api/patients'&&req.method==='POST'){const b=await body(req);if(typeof b.id!=='string'||!/^[-A-Za-z0-9_]{1,64}$/.test(b.id)||!CENTERS[b.center])return json({error:'住院号限字母、数字、连字符和下划线，中心须从列表选择'},400);if(b.name&&String(b.name).length>80||b.phone&&String(b.phone).length>40)return json({error:'姓名或电话过长'},400);const exists=await bundle(db,b.id);if(exists)return json({error:'此住院号已存在，请选择该患者；跨中心重号需先核实，不会覆盖'},409);await db.prepare('INSERT INTO patients(id,center,created,actor,name,phone) VALUES(?,?,?,?,?,?)').bind(b.id,b.center,new Date().toISOString(),actor,String(b.name||'').trim(),String(b.phone||'').trim()).run();return json(await bundle(db,b.id))}
const match=url.pathname.match(/^\/api\/patients\/([^/]+)(?:\/(records|randomize|audit|archive|profile))?$/);if(!match)return json({error:'无此接口'},404);const id=decodeURIComponent(match[1]),operation=match[2],p=await bundle(db,id);if(!p)return json({error:'未找到患者'},404);
if(!operation&&req.method==='GET')return json(p);
if(operation==='audit'&&req.method==='GET'){const a=await db.prepare('SELECT * FROM audit WHERE patient=? ORDER BY id').bind(id).all();return json(a.results)}
if(operation==='archive'&&req.method==='POST'){const b=await body(req),now=new Date().toISOString();if(b.archived===true)await db.prepare('INSERT INTO patient_archives(patient,archived_at,actor) VALUES(?,?,?) ON CONFLICT(patient) DO NOTHING').bind(id,now,actor).run();else if(b.archived===false)await db.prepare('DELETE FROM patient_archives WHERE patient=?').bind(id).run();else return json({error:'删除状态无效'},400);return json({ok:true,archived:b.archived,patient:id})}
if(operation==='profile'&&req.method==='POST'){const b=await body(req),name=String(b.name||'').trim(),phone=String(b.phone||'').trim();if(name.length>80||phone.length>40)return json({error:'姓名或电话过长'},400);await db.prepare('UPDATE patients SET name=?,phone=? WHERE id=?').bind(name,phone,id).run();await db.prepare('INSERT INTO audit(patient,action,after,at,actor) VALUES(?,?,?,?,?)').bind(id,'update_patient_profile',JSON.stringify({name,phone:phone?'已填写':''}),new Date().toISOString(),actor).run();return json(await bundle(db,id))}
if(operation==='records'&&req.method==='POST'){const b=await body(req),m=MODULES.find(x=>x.id===b.module);if(!m||!b.data||typeof b.data!=='object'||Array.isArray(b.data))return json({error:'模块或数据格式错误'},400);if(b.module==='procedure'&&b.data.conforms==='是'){const plan=procedurePlan(p.allocation?.arm);if(!plan)return json({error:'尚未随机化，不能确认按组别方案完成'},400);for(const [key,value] of Object.entries(plan))if(b.data[key]&&b.data[key]!==value)return json({error:'按方案完成时固定项不可改写；请改选否并记录实际操作及偏离原因'},400);b.data={...b.data,...plan}}if(b.module==='procedure'&&b.data.conforms==='否'&&!b.data.deviation?.trim())return json({error:'未按随机组方案完成，请填写偏离原因'},400);const errors=validate(b.module,b.data);if(errors.length)return json({error:errors.join('；')},400);if(p.allocation&&b.module==='random')return json({error:'随机分组时的资格确认与分层已锁定，不可改写'},409);if(p.allocation&&b.module==='baseline'&&b.data.tumor&&(b.data.tumor==='胰腺癌'?'P':'NP')!==p.allocation.stratum)return json({error:'补录肿瘤类型与已锁定随机分层不一致；请核实，不会改变原分组'},409);const slot=m.repeat?b.slot:'main';if(!slot||!/^[-a-zA-Z0-9]{1,80}$/.test(slot))return json({error:'记录标识无效'},400);const now=new Date().toISOString(),recordId=id+':'+b.module+':'+slot,version=Number(b.version)||0;let result;if(!version){result=await db.prepare('INSERT INTO records(id,patient,module,slot,data,version,updated,actor) VALUES(?,?,?,?,?,1,?,?) ON CONFLICT(id) DO NOTHING RETURNING id').bind(recordId,id,b.module,slot,JSON.stringify(b.data),now,actor).all()}else{result=await db.prepare('UPDATE records SET data=?,version=version+1,updated=?,actor=? WHERE id=? AND version=? RETURNING id').bind(JSON.stringify(b.data),now,actor,recordId,version).all()}if(!result.results.length)return json({error:'该记录已在另一页面更新，请刷新读取后再修改；当前输入仍保留'},409);return json(await bundle(db,id))}
if(operation==='randomize'&&req.method==='POST'){if(p.allocation)return json(p);const errors=eligibility(p.records);if(errors.length)return json({error:errors.join('；')},400);const b=p.records.find(r=>r.module==='baseline')?.data||{},r=p.records.find(r=>r.module==='random').data,stratum=r.stratum||(b.tumor==='胰腺癌'?'P':'NP');for(let attempt=0;attempt<8;attempt++){const existing=await db.prepare('SELECT patient,arm,center,stratum FROM allocations ORDER BY seq').all();if(existing.results.some(x=>x.patient===id))return json(await bundle(db,id));const u=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296,plan=allocationPlan(existing.results,p.patient.center,stratum,u),at=new Date().toISOString();const rows=await db.prepare('INSERT INTO allocations(patient,seq,arm,center,stratum,u,score_a,score_b,prob_a,at,actor,operator,inputs) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM allocations)=? AND NOT EXISTS(SELECT 1 FROM allocations WHERE patient=?) AND (SELECT SUM(version) FROM records WHERE patient=? AND module IN (\'screen\',\'baseline\',\'random\'))=? RETURNING patient').bind(id,plan.seq,plan.arm,p.patient.center,stratum,u,plan.scoreA,plan.scoreB,plan.probA,at,actor,r.operator,JSON.stringify(p.records.filter(x=>['screen','baseline','random'].includes(x.module))),existing.results.length,id,id,p.records.filter(x=>['screen','baseline','random'].includes(x.module)).reduce((sum,x)=>sum+x.version,0)).all();if(rows.results.length)return json(await bundle(db,id))}return json({error:'其他中心正在随机化，请稍后重试；本次未分配'},409)}
return json({error:'请求方法不支持'},405)}catch(e){return json({error:e.message?.includes('已达到')?e.message:'操作未完成，请保留输入后重试；如持续出现请联系管理员'},500)}}};
